import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // ── bg ────────────────────────────────────────────────────────────
    "bg-rose-50",
    "bg-sky-50",
    "bg-emerald-50",
    "bg-amber-50",
    "bg-violet-50",
    "bg-slate-50",
    "bg-orange-50",
    "bg-slate-900",
    "bg-red-50",
    "bg-purple-50",
    "bg-green-50",
    "bg-yellow-50",
    "bg-teal-50",
    // ── gradientFrom ──────────────────────────────────────────────────
    "from-rose-100",
    "from-sky-100",
    "from-emerald-100",
    "from-amber-100",
    "from-violet-100",
    "from-orange-100",
    "from-purple-100",
    "from-green-100",
    "from-yellow-100",
    "from-slate-800",
    "from-red-100",
    "from-red-200",
    "from-orange-200",
    "from-teal-100",
    "from-pink-100",
    // ── gradientTo ────────────────────────────────────────────────────
    "to-rose-200",
    "to-sky-200",
    "to-emerald-200",
    "to-amber-200",
    "to-violet-200",
    "to-sky-200",
    "to-orange-200",
    "to-purple-200",
    "to-green-200",
    "to-yellow-200",
    "to-slate-900",
    "to-red-200",
    "to-amber-200",
    "to-amber-950",
    "to-teal-200",
    "to-violet-200",
    "to-green-100",
    "to-rose-100",
    "to-orange-100",
    // ── text ──────────────────────────────────────────────────────────
    "text-rose-900",
    "text-sky-900",
    "text-emerald-900",
    "text-amber-900",
    "text-violet-900",
    "text-slate-900",
    "text-orange-900",
    "text-slate-100",
    "text-red-900",
    "text-purple-900",
    "text-green-900",
    "text-yellow-900",
    "text-teal-900",
    "text-amber-100",
    // ── accent ────────────────────────────────────────────────────────
    "text-rose-600",
    "text-sky-600",
    "text-emerald-600",
    "text-amber-600",
    "text-violet-600",
    "text-slate-600",
    "text-orange-600",
    "text-cyan-400",
    "text-red-500",
    "text-purple-600",
    "text-green-700",
    "text-yellow-600",
    "text-teal-600",
    "text-amber-700",
    "text-amber-400",
    "text-pink-600",
    // ── border ────────────────────────────────────────────────────────
    "border-rose-300",
    "border-sky-300",
    "border-emerald-300",
    "border-amber-300",
    "border-violet-300",
    "border-slate-300",
    "border-orange-300",
    "border-cyan-400",
    "border-red-300",
    "border-purple-300",
    "border-green-300",
    "border-yellow-300",
    "border-teal-300",
    "border-orange-400",
    "border-amber-500",
    "border-pink-300",
    // ── ring ──────────────────────────────────────────────────────────
    "ring-rose-200",
    "ring-sky-200",
    "ring-emerald-200",
    "ring-amber-200",
    "ring-violet-200",
    "ring-slate-200",
    "ring-orange-200",
    "ring-cyan-300",
    "ring-red-200",
    "ring-purple-200",
    "ring-green-200",
    "ring-yellow-200",
    "ring-teal-200",
    "ring-amber-400",
    "ring-pink-200",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        darkTeal: "var(--dark-teal)",
      },
    },
  },
  plugins: [],
};
export default config;
