import type { CardCategory } from "./types";

export const CATEGORIES: CardCategory[] = [
  // ── Evergreen / life occasions ──────────────────────────────────────
  {
    id: "birthday",
    label: "Birthday",
    emoji: "🎂",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FFD700", "#00BFFF", "#FF4500", "#7FFF00"],
    greeting: "Happy Birthday!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "Wishing you all the joy your heart can hold today! 🎂",
      "May this birthday be the start of your best year yet! 🎉",
      "Here's to you — celebrate every single moment today! 🥳",
      "Sending you so much love on your special day! 🎁",
    ],
  },
  {
    id: "anniversary",
    label: "Anniversary",
    emoji: "💕",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FF1493", "#FFD700", "#FF0000"],
    greeting: "Happy Anniversary!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "Celebrating your beautiful love story today! 💕",
      "Another year of love, laughter, and wonderful memories. 🥂",
      "Your love is an inspiration to everyone around you! ❤️",
      "Wishing you many more years of happiness together! 💑",
    ],
  },
  {
    id: "thank-you",
    label: "Thank You",
    emoji: "🙏",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FFA500", "#FF8C00", "#FFFACD"],
    greeting: "Thank You!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Your kindness means more than words can say. 🙏",
      "So grateful to have someone as thoughtful as you in my life! 💛",
      "Thank you from the bottom of my heart! 🌸",
      "Your generosity and care are truly appreciated! ✨",
    ],
  },
  {
    id: "get-well",
    label: "Get Well",
    emoji: "🌷",
    allowConfetti: false,
    greeting: "Get Well Soon!",
    defaultCelebration: "petals",
    sampleMessages: [
      "Sending warm hugs and healing thoughts your way. 🌷",
      "Wishing you a speedy and comfortable recovery! 💙",
      "Rest up — we can't wait to see you back to your wonderful self! 🌻",
      "Thinking of you and sending all my love! 🤗",
    ],
  },
  {
    id: "congrats",
    label: "Congratulations",
    emoji: "🎉",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF4500", "#00BFFF", "#FF69B4", "#7FFF00"],
    greeting: "Congratulations!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "You did it! I am so incredibly proud of you! 🏆",
      "Your hard work and dedication paid off — this is amazing! 🎉",
      "Celebrating this huge achievement with you! ⭐",
      "This is just the beginning of even greater things to come! 🌟",
    ],
  },
  {
    id: "just-because",
    label: "Just Because",
    emoji: "🌸",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FFB6C1", "#FFD700", "#98FB98"],
    greeting: "Just Because!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Just wanted to let you know I'm thinking of you! 🌸",
      "No special reason — just sending love your way today! 💝",
      "You deserve a little smile today, just because you're amazing! ✨",
      "Thinking of you and wishing you a wonderful day! 🌈",
    ],
  },
  {
    id: "thinking-of-you",
    label: "Thinking of You",
    emoji: "💭",
    allowConfetti: false,
    greeting: "Thinking of You",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "You've been on my mind and in my heart. 💭",
      "Just a little note to say I'm thinking of you today! 💙",
      "Sending warmth and love your way! 🌻",
      "Distance means nothing — you're always in my thoughts! 💛",
    ],
  },
  {
    id: "good-luck",
    label: "Good Luck",
    emoji: "🍀",
    allowConfetti: true,
    confettiColors: ["#00FF00", "#90EE90", "#FFD700", "#32CD32"],
    greeting: "Good Luck!",
    defaultCelebration: "stars",
    sampleMessages: [
      "Rooting for you every single step of the way! 🍀",
      "You've absolutely got this! Sending all my positive energy! ⭐",
      "Wishing you the very best — go show them what you've got! 🌟",
      "All my luck is yours today! You're going to be amazing! 🎯",
    ],
  },
  {
    id: "welcome",
    label: "Welcome",
    emoji: "🏠",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF69B4", "#00BFFF", "#98FB98"],
    greeting: "Welcome!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "So thrilled to have you here — this is just the beginning! 🏠",
      "Warmest welcome! Can't wait to make wonderful memories together! 🎉",
      "A new chapter begins — welcome! We are so happy you're here! 🌟",
      "You are going to love it here — welcome! ✨",
    ],
  },
  {
    id: "miss-you",
    label: "Miss You",
    emoji: "💙",
    allowConfetti: false,
    greeting: "Miss You!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "Life is just not the same without you around! 💙",
      "Every day I think of you and smile. Miss you loads! 💝",
      "Can't wait for us to be together again soon! 🤗",
      "Sending hugs across the miles — miss you so much! 💛",
    ],
  },
  {
    id: "sympathy",
    label: "Sympathy",
    emoji: "🕊️",
    allowConfetti: false,
    greeting: "With Deepest Sympathy",
    defaultCelebration: "none",
    sampleMessages: [
      "Holding you gently in my thoughts during this difficult time. 🕊️",
      "There are no words for how sorry I am for your loss. 💙",
      "May you find peace and comfort in the love of those around you. 🌿",
      "Sending you strength and love as you walk through this time. 💛",
    ],
  },

  // ── American holidays ───────────────────────────────────────────────
  {
    id: "new-year",
    label: "New Year",
    emoji: "🎆",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#C0C0C0", "#FF69B4", "#FFFFFF"],
    greeting: "Happy New Year!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "Wishing you a year filled with joy, health, and happiness! 🎆",
      "May the new year bring you everything your heart desires! ✨",
      "Here's to new beginnings and wonderful adventures ahead! 🥂",
      "Cheers to a brand new year full of blessings! 🎉",
    ],
  },
  {
    id: "valentines",
    label: "Valentine's Day",
    emoji: "❤️",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FF0000", "#FF1493", "#FFB6C1"],
    greeting: "Happy Valentine's Day!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "You make every single day feel like Valentine's Day! ❤️",
      "Grateful every day that you are in my life. Love you! 💕",
      "Sending you all my love and sweetest wishes today! 💝",
      "You are the best thing that ever happened to me! 💖",
    ],
  },
  {
    id: "easter",
    label: "Easter",
    emoji: "🐣",
    allowConfetti: true,
    confettiColors: ["#FFB6C1", "#98FB98", "#FFFACD", "#B0E0E6", "#DDA0DD"],
    greeting: "Happy Easter!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Wishing you a joyful Easter filled with love and blessings! 🐣",
      "May this Easter bring you renewed hope and happiness! 🌸",
      "Sending Easter joy your way — hope it's a beautiful day! 🐰",
      "Wishing you and your family a blessed and beautiful Easter! 🌷",
    ],
  },
  {
    id: "mothers-day",
    label: "Mother's Day",
    emoji: "🌹",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FFB6C1", "#FF1493", "#C71585"],
    greeting: "Happy Mother's Day!",
    defaultCelebration: "petals",
    sampleMessages: [
      "Thank you for your endless love and everything you do! 🌹",
      "You are the heart of our family. We love you so much! 💕",
      "No words can ever express how much you mean to us! ❤️",
      "To the most amazing mom — thank you for being you! 🌸",
    ],
  },
  {
    id: "fathers-day",
    label: "Father's Day",
    emoji: "👔",
    allowConfetti: true,
    confettiColors: ["#1E90FF", "#4169E1", "#FFD700", "#87CEEB"],
    greeting: "Happy Father's Day!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "Thank you for always being there and making us feel so loved! 👔",
      "To the world's best dad — this day is all about you! 🏆",
      "Your strength, wisdom, and humor make every day better! ❤️",
      "So grateful to have a dad like you. Love you so much! 💙",
    ],
  },
  {
    id: "independence-day",
    label: "Independence Day",
    emoji: "🎇",
    allowConfetti: true,
    confettiColors: ["#FF0000", "#FFFFFF", "#0000FF", "#FFD700"],
    greeting: "Happy 4th of July!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "Wishing you a wonderful 4th filled with family, fun, and fireworks! 🎇",
      "Celebrating freedom and all the amazing things that make this country great! 🇺🇸",
      "Happy Independence Day! Hope your day is absolutely spectacular! 🎆",
      "Sending warm patriotic wishes to you and your family! ⭐",
    ],
  },
  {
    id: "halloween",
    label: "Halloween",
    emoji: "🎃",
    allowConfetti: false,
    greeting: "Happy Halloween!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Hope your Halloween is delightfully spooky and full of treats! 🎃",
      "Wishing you a night full of tricks, treats, and happy frights! 👻",
      "May your Halloween be wickedly wonderful! 🕷️",
      "Have a frighteningly fun Halloween — stay safe out there! 🦇",
    ],
  },
  {
    id: "thanksgiving",
    label: "Thanksgiving",
    emoji: "🦃",
    allowConfetti: true,
    confettiColors: ["#FF8C00", "#D2691E", "#DAA520", "#8B4513"],
    greeting: "Happy Thanksgiving!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "So grateful for the wonderful people in my life — especially you! 🦃",
      "Wishing you a warm Thanksgiving surrounded by love and good food! 🍂",
      "Today and every day, I am so thankful for you! 🌽",
      "May your table be full and your heart even fuller! 🍁",
    ],
  },
  {
    id: "christmas",
    label: "Christmas",
    emoji: "🎄",
    allowConfetti: true,
    confettiColors: ["#FF0000", "#228B22", "#FFD700", "#FFFFFF"],
    greeting: "Merry Christmas!",
    defaultCelebration: "snow",
    sampleMessages: [
      "Wishing you a magical Christmas filled with love and laughter! 🎄",
      "May your holiday be as wonderful as you are! ⭐",
      "Sending warmest Christmas wishes to you and your loved ones! 🎅",
      "May joy, love, and peace fill your home this Christmas! 🎁",
    ],
  },

  // ── Hindu / Gujarati / Indian holidays ─────────────────────────────
  {
    id: "makar-sankranti",
    label: "Makar Sankranti",
    emoji: "🪁",
    allowConfetti: true,
    confettiColors: ["#87CEEB", "#FFFFFF", "#FFD700", "#FF69B4"],
    greeting: "Happy Makar Sankranti!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May your life soar high like a kite this Makar Sankranti! 🪁",
      "Wishing you a harvest of joy and success this Sankranti! 🌾",
      "Til gul ghya, god god bola — wishing you sweetness always! 🌅",
      "May this auspicious day bring warmth and happiness into your life! ✨",
    ],
  },
  {
    id: "lohri",
    label: "Lohri",
    emoji: "🔥",
    allowConfetti: true,
    confettiColors: ["#FF4500", "#FF8C00", "#FFD700", "#FFA500"],
    greeting: "Happy Lohri!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May the bonfire of Lohri brighten your life with joy and prosperity! 🔥",
      "Wishing you and your family a warm and wonderful Lohri! 🎶",
      "Sundari mundariye ho! May this Lohri be filled with love! 🌾",
      "May the sacred flames of Lohri fill your heart with happiness! ✨",
    ],
  },
  {
    id: "pongal",
    label: "Pongal",
    emoji: "🍚",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#228B22", "#FF69B4"],
    greeting: "Happy Pongal!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Pongal O Pongal! May this harvest festival bring abundance! 🍚",
      "Wishing you a Pongal filled with sweetness and prosperity! ☀️",
      "May this Pongal mark new beginnings and joy for your family! 🌾",
      "Sending warm Pongal wishes — may your harvest always be plentiful! ✨",
    ],
  },
  {
    id: "vasant-panchami",
    label: "Vasant Panchami",
    emoji: "🌼",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FFFF00", "#FFF44F", "#FFFACD"],
    greeting: "Happy Vasant Panchami!",
    defaultCelebration: "petals",
    sampleMessages: [
      "May Goddess Saraswati bless you with wisdom and creativity! 🌼",
      "Wishing you a golden Vasant Panchami filled with learning and joy! ✨",
      "May this day bring the freshness of spring into your life! 🌸",
      "Saraswati Puja greetings — may knowledge light your path! 💛",
    ],
  },
  {
    id: "mahashivratri",
    label: "Mahashivratri",
    emoji: "🔱",
    allowConfetti: false,
    greeting: "Happy Mahashivratri!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May Lord Shiva's blessings fill your life with peace and joy! 🔱",
      "Har Har Mahadev! Wishing you a blessed Mahashivratri! 🙏",
      "May this holy night bring divine blessings to you and your family! ✨",
      "Wishing you a serene and spiritually fulfilling Mahashivratri! 🕉️",
    ],
  },
  {
    id: "holi",
    label: "Holi",
    emoji: "🎨",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#00CED1", "#32CD32", "#FFD700", "#9400D3", "#FF4500", "#00FA9A"],
    greeting: "Happy Holi!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "May the colours of Holi fill your life with joy, love, and happiness! 🎨",
      "Wishing you a vibrant and joyful Holi — Bura na mano, Holi hai! 🌈",
      "May every colour of Holi bring you a new reason to smile! 🎊",
      "Sending you a rainbow of Holi blessings! ✨",
    ],
  },
  {
    id: "gudi-padwa",
    label: "Gudi Padwa",
    emoji: "🪇",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#FF69B4", "#00CED1"],
    greeting: "Shubh Gudi Padwa!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "May this New Year bring you health, wealth, and prosperity! 🪇",
      "Wishing you and your family a blessed and joyful Gudi Padwa! ✨",
      "May the Gudi of your life always fly high with success! 🌅",
      "Shubhechha! May this new beginning bring all your dreams to life! 🎉",
    ],
  },
  {
    id: "ram-navami",
    label: "Ram Navami",
    emoji: "🙏",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#228B22", "#FFFFFF"],
    greeting: "Happy Ram Navami!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May the blessings of Lord Ram bring peace and joy to your home! 🙏",
      "Wishing you a blessed Ram Navami filled with devotion and happiness! ✨",
      "Jai Shri Ram! May Lord Ram's grace always be with you! 🌸",
      "May this auspicious day fill your life with divine blessings! 💛",
    ],
  },
  {
    id: "hanuman-jayanti",
    label: "Hanuman Jayanti",
    emoji: "🌺",
    allowConfetti: true,
    confettiColors: ["#FF4500", "#FF8C00", "#FFD700"],
    greeting: "Happy Hanuman Jayanti!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Jai Bajrangbali! May Lord Hanuman bless you with strength and courage! 🌺",
      "May the devotion of Lord Hanuman inspire you on this blessed day! 🙏",
      "Wishing you a spiritually blessed Hanuman Jayanti! ✨",
      "May Lord Hanuman's blessings keep you protected and joyful always! 🌸",
    ],
  },
  {
    id: "akshaya-tritiya",
    label: "Akshaya Tritiya",
    emoji: "💛",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FFA500", "#DAA520", "#FFFACD"],
    greeting: "Happy Akshaya Tritiya!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May this auspicious day bring you unending prosperity and happiness! 💛",
      "Wishing you a blessed Akshaya Tritiya filled with abundance! ✨",
      "May all your beginnings on this day bring lasting fortune! 🌟",
      "Sending golden wishes for a wonderful Akshaya Tritiya! 🪙",
    ],
  },
  {
    id: "baisakhi",
    label: "Baisakhi",
    emoji: "🌾",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#228B22", "#FF4500"],
    greeting: "Happy Baisakhi!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "Wishing you a harvest of joy and blessings this Baisakhi! 🌾",
      "May the spirit of Baisakhi bring new hope and happiness to your life! 🎉",
      "Baisakhi Mubarak! May your fields of life always be abundant! ✨",
      "Celebrating the harvest festival with warm wishes for you! 🌅",
    ],
  },
  {
    id: "rath-yatra",
    label: "Rath Yatra",
    emoji: "🎠",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#FF4500", "#FFFFFF"],
    greeting: "Happy Rath Yatra!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Jai Jagannath! May Lord Jagannath's blessings guide your journey! 🎠",
      "May the sacred chariot procession bring blessings into your life! 🙏",
      "Wishing you a blessed and joyful Rath Yatra! ✨",
      "May Lord Jagannath always shower his grace and love upon you! 🌸",
    ],
  },
  {
    id: "janmashtami",
    label: "Janmashtami",
    emoji: "🦚",
    allowConfetti: true,
    confettiColors: ["#00CED1", "#1E90FF", "#FFD700", "#FF69B4"],
    greeting: "Happy Janmashtami!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "Nand ke Anand Bhayo, Jai Kanhaiya Lal Ki! Happy Janmashtami! 🦚",
      "May Lord Krishna's divine love and blessings fill your heart! 🌸",
      "Wishing you a blessed Janmashtami filled with joy and devotion! ✨",
      "May Baal Gopal's blessings bring you happiness and prosperity! 💙",
    ],
  },
  {
    id: "onam",
    label: "Onam",
    emoji: "🌸",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF69B4", "#32CD32", "#FF8C00"],
    greeting: "Happy Onam!",
    defaultCelebration: "petals",
    sampleMessages: [
      "May the spirit of Onam fill your home with happiness and prosperity! 🌸",
      "Wishing you a joyful harvest festival with loved ones! 🌺",
      "May King Mahabali's blessings bring peace to your family! ✨",
      "Onam Ashamsakal! May this festival bring you all the joy in the world! 🌼",
    ],
  },
  {
    id: "ganesh-chaturthi",
    label: "Ganesh Chaturthi",
    emoji: "🐘",
    allowConfetti: true,
    confettiColors: ["#FF8C00", "#FFD700", "#FF4500", "#FFA500"],
    greeting: "Ganpati Bappa Morya!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "May Lord Ganesha remove all obstacles from your path! 🐘",
      "Wishing you a blessed Ganesh Chaturthi filled with joy and prosperity! 🌺",
      "May Bappa's blessings bring wisdom, success, and happiness to you! ✨",
      "Ganpati Bappa Morya! May your every wish come true! 💛",
    ],
  },
  {
    id: "navratri",
    label: "Navratri",
    emoji: "🎭",
    allowConfetti: true,
    confettiColors: ["#FF4500", "#FF8C00", "#FFD700", "#FF69B4", "#9400D3"],
    greeting: "Happy Navratri!",
    defaultCelebration: "confetti",
    sampleMessages: [
      "Wishing you nine days of divine blessings and joyful celebration! 🎭",
      "May Maa Durga's blessings fill your life with strength and happiness! ✨",
      "Jai Mata Di! May this Navratri bring prosperity to your home! 🌺",
      "May the auspicious festival of Navratri bring love and light to your life! 🌸",
    ],
  },
  {
    id: "karva-chauth",
    label: "Karva Chauth",
    emoji: "🌕",
    allowConfetti: false,
    greeting: "Happy Karva Chauth!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "May your love grow stronger with each passing year! 🌕",
      "Wishing you a blessed Karva Chauth filled with love and togetherness! 💕",
      "May the bond you share be as eternal as the stars! ✨",
      "Sending warm Karva Chauth wishes to you and your beloved! 🌸",
    ],
  },
  {
    id: "dhanteras",
    label: "Dhanteras",
    emoji: "🪙",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#DAA520", "#FFA500", "#FFFACD"],
    greeting: "Happy Dhanteras!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May Goddess Lakshmi bless your home with wealth and prosperity! 🪙",
      "Wishing you a golden Dhanteras filled with good fortune! ✨",
      "May this Dhanteras bring happiness and abundance to your family! 💛",
      "Shubh Dhanteras! May your home overflow with Lakshmi's blessings! 🌺",
    ],
  },
  {
    id: "diwali",
    label: "Diwali",
    emoji: "🪔",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF6B35", "#FF4500", "#FFA500", "#FFFACD"],
    greeting: "Happy Diwali!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "May the festival of lights fill your home with joy and prosperity! 🪔",
      "Wishing you a bright and beautiful Diwali with your loved ones! ✨",
      "May Diwali bring happiness, health, and wealth to you and your family! 🌟",
      "Shubh Deepawali! May every lamp light up your world with love! 💛",
    ],
  },
  {
    id: "bhai-dooj",
    label: "Bhai Dooj",
    emoji: "👫",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FFD700", "#FF8C00", "#FF1493"],
    greeting: "Happy Bhai Dooj!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "Celebrating the beautiful bond of siblings on this special day! 👫",
      "May the love between us grow stronger every single day! 💕",
      "Wishing you a wonderful Bhai Dooj filled with cherished memories! ✨",
      "To the best sibling ever — thank you for always being there! 🌸",
    ],
  },
  {
    id: "gujarati-new-year",
    label: "Gujarati New Year",
    emoji: "🌅",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#FF4500", "#FF69B4"],
    greeting: "Saal Mubarak!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "Nutan Varshabhinandan! May this new year bring you joy and prosperity! 🌅",
      "Wishing you a wonderful Gujarati New Year filled with happiness! ✨",
      "May this new year mark new heights of success and joy for you! 🎉",
      "Saal Mubarak! May Lakshmi's blessings shower upon you always! 💛",
    ],
  },
  {
    id: "chhath-puja",
    label: "Chhath Puja",
    emoji: "☀️",
    allowConfetti: false,
    greeting: "Happy Chhath Puja!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May Chhath Maiya's blessings bring health and happiness to you! ☀️",
      "Wishing you a blessed Chhath Puja filled with devotion and joy! 🙏",
      "May the rising sun fill your life with brightness and prosperity! ✨",
      "Chhath Maiyya ki Jai! May you and your family always be blessed! 💛",
    ],
  },
  {
    id: "dussehra",
    label: "Dussehra",
    emoji: "⚔️",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF4500", "#FF8C00", "#FFFFFF"],
    greeting: "Happy Dussehra!",
    defaultCelebration: "fireworks",
    sampleMessages: [
      "May good always triumph over evil in your life! ⚔️",
      "Wishing you a victorious Dussehra filled with joy and blessings! ✨",
      "May this Dussehra mark the victory of positivity in your life! 🌟",
      "Jai Shri Ram! Wishing you and your family a blessed Dussehra! 💛",
    ],
  },
  {
    id: "raksha-bandhan",
    label: "Raksha Bandhan",
    emoji: "🪢",
    allowConfetti: true,
    confettiColors: ["#FF69B4", "#FFD700", "#FF1493", "#FF8C00"],
    greeting: "Happy Raksha Bandhan!",
    defaultCelebration: "hearts",
    sampleMessages: [
      "Celebrating the unbreakable bond between siblings on this special day! 🪢",
      "May the thread of love and care always keep us connected! 💕",
      "To my favourite sibling — thank you for everything you are to me! 🌸",
      "Wishing you a beautiful Raksha Bandhan filled with love! ✨",
    ],
  },
  {
    id: "guru-nanak-jayanti",
    label: "Guru Nanak Jayanti",
    emoji: "🕊️",
    allowConfetti: true,
    confettiColors: ["#FFD700", "#FF8C00", "#0000FF", "#FFFFFF"],
    greeting: "Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!",
    defaultCelebration: "sparkles",
    sampleMessages: [
      "May Guru Nanak Dev Ji's blessings bring peace and love to your life! 🕊️",
      "Wishing you a blessed Gurpurab filled with devotion and happiness! ✨",
      "May the teachings of Guru Nanak guide and inspire you always! 🌸",
      "Sending warm Gurpurab greetings to you and your family! 💛",
    ],
  },
];
