import type { ColorTheme } from "./types";

export const THEMES: ColorTheme[] = [
  {
    id: "rose-garden",
    label: "Rose Garden",
    bg: "bg-rose-50",
    gradientFrom: "from-rose-100",
    gradientTo: "to-rose-200",
    text: "text-rose-900",
    accent: "text-rose-600",
    border: "border-rose-300",
    ring: "ring-rose-200",
  },
  {
    id: "sky-blue",
    label: "Sky Blue",
    bg: "bg-sky-50",
    gradientFrom: "from-sky-100",
    gradientTo: "to-sky-200",
    text: "text-sky-900",
    accent: "text-sky-600",
    border: "border-sky-300",
    ring: "ring-sky-200",
  },
  {
    id: "emerald",
    label: "Emerald",
    bg: "bg-emerald-50",
    gradientFrom: "from-emerald-100",
    gradientTo: "to-emerald-200",
    text: "text-emerald-900",
    accent: "text-emerald-600",
    border: "border-emerald-300",
    ring: "ring-emerald-200",
  },
  {
    id: "amber-gold",
    label: "Amber Gold",
    bg: "bg-amber-50",
    gradientFrom: "from-amber-100",
    gradientTo: "to-amber-200",
    text: "text-amber-900",
    accent: "text-amber-600",
    border: "border-amber-300",
    ring: "ring-amber-200",
  },
  {
    id: "violet",
    label: "Violet",
    bg: "bg-violet-50",
    gradientFrom: "from-violet-100",
    gradientTo: "to-violet-200",
    text: "text-violet-900",
    accent: "text-violet-600",
    border: "border-violet-300",
    ring: "ring-violet-200",
  },
  {
    id: "slate-clean",
    label: "Slate Clean",
    bg: "bg-slate-50",
    gradientFrom: "from-sky-100",
    gradientTo: "to-sky-200",
    text: "text-slate-900",
    accent: "text-slate-600",
    border: "border-slate-300",
    ring: "ring-slate-200",
  },
  {
    id: "warm-cream",
    label: "Warm Cream",
    bg: "bg-orange-50",
    gradientFrom: "from-orange-100",
    gradientTo: "to-orange-200",
    text: "text-orange-900",
    accent: "text-orange-600",
    border: "border-orange-300",
    ring: "ring-orange-200",
  },
  {
    id: "midnight",
    label: "Midnight",
    bg: "bg-slate-900",
    gradientFrom: "from-slate-800",
    gradientTo: "to-slate-900",
    text: "text-slate-100",
    accent: "text-cyan-400",
    border: "border-cyan-400",
    ring: "ring-cyan-300",
  },
  {
    id: "peach",
    label: "Peach",
    bg: "bg-red-50",
    gradientFrom: "from-red-100",
    gradientTo: "to-red-200",
    text: "text-red-900",
    accent: "text-red-500",
    border: "border-red-300",
    ring: "ring-red-200",
  },
  {
    id: "lavender",
    label: "Lavender",
    bg: "bg-purple-50",
    gradientFrom: "from-purple-100",
    gradientTo: "to-purple-200",
    text: "text-purple-900",
    accent: "text-purple-600",
    border: "border-purple-300",
    ring: "ring-purple-200",
  },
  {
    id: "mint",
    label: "Mint",
    bg: "bg-green-50",
    gradientFrom: "from-green-100",
    gradientTo: "to-green-200",
    text: "text-green-900",
    accent: "text-green-700",
    border: "border-green-300",
    ring: "ring-green-200",
  },
  {
    id: "sunshine",
    label: "Sunshine",
    bg: "bg-yellow-50",
    gradientFrom: "from-yellow-100",
    gradientTo: "to-yellow-200",
    text: "text-yellow-900",
    accent: "text-yellow-600",
    border: "border-yellow-300",
    ring: "ring-yellow-200",
  },
];
