"""
Five fully independent image briefs per e-card occasion (225 prompts total).

Each string stands alone (composition + lighting + medium); scripts/ecard_background_data.py
prepends shared GUARDRAILS — there is no shared “scene + style overlay” anymore.
"""

from __future__ import annotations

# category_id -> exactly five distinct prompts (stable order 01–05).
PROMPTS_BY_CATEGORY: dict[str, tuple[str, str, str, str, str]] = {
    "akshaya-tritiya": (
        "Gold-trim jewelry boxes half-open on mustard brocade, stacked mango leaves, a tiny brass weighing scale with stylized coins — tight tabletop watercolor with soft side light and quiet negative space above.",
        "Wide balcony at auspicious hour: silk saree pallu catching breeze, temple tops far away as pale silhouettes, scattered rose petals on marble — gouache memory-piece with airy sky band for text.",
        "Bold decorative frame of mango leaves and coin motifs around a hazy cream void; flat dignified cartoon geometry with jewel accents — greeting-card border layout, center deliberately plain.",
        "Painterly shop-window feeling: necklaces on velvet, marigold strand draped over corner, hand reaching in only as soft glove-shape blur — golden-hour warmth, nostalgic commerce blessing.",
        "Dreamy upward tilt: tree canopy with newly bought bangles catching sun sparkles, lentil-sized confetti of gold foil shapes drifting — sentimental soft bloom at edges, tender prosperity mood.",
    ),
    "anniversary": (
        "Two mismatched cups of chai steaming on a lacquer tray, rose petals forming a loose heart, fairy lights out of focus behind — intimate watercolor still life.",
        "Moonlit terrace wide shot: empty swing with cushion, distant city pearls of light, single slice of cake under glass dome — calm gouache night romance with pale central sky.",
        "Art-nouveau border of intertwined rings and jasmine loops enclosing soft blush gradient center — lithograph-inspired flat color, anniversary formal.",
        "Rain-streaked window from inside; two plates with half-eaten jalebi, wedding invite envelope edge visible — cozy sentimental realism-as-painting, foggy glass glow.",
        "Abstract golden ribbons weaving through floating carnation petals and tiny bell silhouettes — ethereal illustrative celebration without faces.",
    ),
    "baisakhi": (
        "Harvest tabletop: brass bowl of wheat ears, yellow dupatta fold, dhol skin peeking at frame edge — sunny watercolor textures.",
        "Sweeping mustard-field horizon under mild haze, lone scarecrow hat shape, kite dot far up — wide pastoral gouache band across middle kept pale.",
        "Geometric bhangra-color triangles and wheat stalk icons forming festive ring around empty wheat-toned core — crisp folk-poster cartoon.",
        "Village lane at dusk: drum procession suggested by rhythmic lantern blobs only, dust motes in amber light — painterly motion blur kindness.",
        "Basket of fresh rotis covered by cloth, churn of white butter motif, scattered jasmine — tender kitchen gratitude composition.",
    ),
    "bhai-dooj": (
        "Aarti thali close-up: rice grains, kumkum, flower petals, brass glow — miniature-detail watercolor, sibling ritual warmth.",
        "Courtyard steps with sibling-height diyas leading upward, toran swaying, soft afternoon shadow stripes — medium-wide gouache story scene.",
        "Rakhi-thread mandala border with ladoos pattern corners around misty sage center — decorative flat illustration.",
        "Teenager-scale silhouette figures exchanging plate at doorway — distant chalky shapes only, sunset sentimental wash.",
        "Marble slab with two ladoos, sindoor dabbi, tiny mirror fragment reflecting diya — poetic macro still life.",
    ),
    "birthday": (
        "Countertop cake with gentle candle flames, brass mithai plate, popped balloon shapes as paper scraps — daylight watercolor cheer.",
        "Living-room corner with streamers drooping, wrapped gift stack, empty armchair — gouache domestic celebration leaving wall pale.",
        "Circular balloon wreath illustration framing sky-blue empty oval — playful rounded cartoon for elders.",
        "Rooftop dusk with fairy-light bokeh curtain, cake outline on side table, first stars — golden nostalgic painterly.",
        "Confetti rain frozen mid-air above lace tablecloth; steam wisps from unseen chai — whimsical sentimental freeze-frame.",
    ),
    "chhath-puja": (
        "Riverbank before sunrise: sugarcane arch mirrored faintly in still water, soop with thekuwa — cool teal watercolor horizon.",
        "Wide ghats with distant stove smoke curls as pale gray ribbons, marigold boats suggested — atmospheric gouache devotion.",
        "Sun-disk halo motif rising between geometric river waves border — symbolic flat devotional poster inner calm.",
        "Tiny worshippers as colored silhouette beads along shoreline curve facing apricot sky — soft monumental scale.",
        "Basket of seasonal fruits and brass ghagar beside folded yellow cloth — intimate harvest-offering still life.",
    ),
    "christmas": (
        "Windowsill pine branches dusted with sugar-snow, ruby ribbon bow, candle flame oval — cozy watercolor interior.",
        "Snowy lane widened: warmly lit cottage dot, sled marks as curved lines only — storybook gouache landscape.",
        "Repeating holly and bell border around snowy pearl center — vintage greeting-card flat graphic.",
        "Hot cocoa mug close-up with marshmallows, cinnamon stick cross, twinkle lights bokeh — sentimental warmth macro.",
        "Starburst above stable silhouette far away; angel-wing suggestion as abstract feather arcs — gentle devotional abstraction.",
    ),
    "congrats": (
        "Podium-empty victory scene: gold foil confetti curtain, laurel wreath flat prop leaning — bright watercolor parade.",
        "Hallway perspective with trophy silhouette on pedestal end, spotlight ellipse on floor — cinematic gouache restraint.",
        "Exploding starburst ribbon frame with medal icons corners — graphic celebration inner field soft gray.",
        "Firework pollen drifting over stacked offer letters tied with red thread — tender achievement nostalgia.",
        "Sprouting plant breaking through soil mound beside tiny trophy charm — metaphorical growth congratulation.",
    ),
    "dhanteras": (
        "Polished brass lota lineup reflecting lamp flame, single stylized silver coin leaning, marigold strand — lustrous watercolor metal study.",
        "Shop entrance draped with mango toran, scales silhouette inside darkness, warm spill light — evening gouache commerce blessing.",
        "Geometric coin-and-lamp tessellation border around pale gold void — auspicious flat pattern.",
        "Hands silhouetted arranging diyas only as glowing palm negatives — mystical minimalist devotion.",
        "New broom propped beside brass vessels and scattered petals — domestic prosperity humor gentle.",
    ),
    "diwali": (
        "Serried clay diyas along curved marble steps, smoke wisps thin, toran overhead heavy with marigolds — classic evening watercolor.",
        "Terrace overview of neighborhood lamp constellations under indigo sky, one rocket trail pastel — wide sentimental panorama.",
        "Rangoli geometry snapshot from above: rice-flour whitelines and powder wedges surrounding plain inner circle — crisp graphic festive.",
        "Brass urli overflowing roses and floating candles seen top-down — symmetrical miniature luxury.",
        "Child-height sparkler scribbles as warm orange ligatures against velvet dusk — motion-memory painterly.",
    ),
    "dussehra": (
        "Fallen silk bows and toy bows/arrows arranged decoratively on marigold carpet, evening violet sky — symbolic watercolor pause.",
        "Ramlila ground suggested by distant paper-effigy silhouette tiny against ridge line, crowds as soft color chips — wide gouache dusk.",
        "Ten-headed stylized mask motif as flat papercraft collage corners — graphic epic reminder without horror.",
        "Archer silhouette releasing flame-lit arrow as curved ribbon shape only — kinetic miniature illustration.",
        "Lotus pond moonrise with floating lamps pulling gaze outward — serene triumph abstraction.",
    ),
    "easter": (
        "Garden close-up: speckled eggs nested in grass rosette, dew pearls, shy tulip cups — spring watercolor freshness.",
        "Hilltop sunrise band widening over sleepy village roofs, bell tower dot — hopeful gouache panorama.",
        "Easter lily silhouette ring border around pastel yellow calm — elegant liturgical flat graphic.",
        "Baking cooling rack with cross-shaped hot-cross bun rhythm — cozy domestic renewal sentimental.",
        "Butterfly quartet ascending diagonal across mint sky — resurrection lightness cartoon-soft.",
    ),
    "fathers-day": (
        "Weathered wood desk: folded newspaper, rimmed spectacles, steel flask catching window stripe — quiet watercolor tribute.",
        "Balcony railing with potted curry-leaf plant, newspaper kite stuck decorative, chai cooling — domestic gouache portrait-of-absence.",
        "Toolbox interior flat lay: tape measure heart-shape accident, screws spelling vague initials — gentle humor illustration.",
        "Park bench empty save hat and walking stick leaning — golden hour sentimental silhouette props.",
        "Night desk lamp cone illuminating handwritten letter page blank center — contemplative warmth.",
    ),
    "ganesh-chaturthi": (
        "Clay Ganesha murti softened into gouache curves with modak pyramid foreground, marigold heaps — stylized eye-level shrine tabletop.",
        "Street procession blur: umbrellas as mushroom caps, fairy-string arcs, distant idol palanquin glow — wide kinetic memory.",
        "Paisley-modak repeating frame around hazy saffron heart — decorative cartoon devotion.",
        "Mouse vahana suggested as tiny plush curve near footprint stamps on rangoli — whimsical tender detail.",
        "Immersion waterfront pre-dawn with mirrored lanterns ribbon — melancholic festive watercolor.",
    ),
    "get-well": (
        "Sunlit sill: tulsi in terracotta, honey jar, sliced citrus wheel, thermometer as pale prop — healing watercolor clarity.",
        "Bedside tray with soup bowl steam arabesque, tissue box covered in floral sleeve — intimate gouache care.",
        "Get-well card tower tied with twine beside lavender sprig — still-life optimism graphic-lite.",
        "Garden path leading to bench under blooming tree — restorative landscape sentimental.",
        "Soft quilt macro folds forming mountain ranges with pill-box sunrise — cozy abstraction comfort.",
    ),
    "good-luck": (
        "Mango-leaf toran tight macro with dew, brass kalash lip gleaming — auspicious watercolor doorway.",
        "Starting-line stadium seats empty but flags fluttering, horseshoe charm on rail — wide motivational gouache.",
        "Four-leaf clover motif tessellation border (fusion whimsy) around pale jade field — playful dignified graphic.",
        "Exam hall clock softened to watercolor donut, sharpened pencils bouquet — gentle student blessing.",
        "Diya constellation forming arrow shape across courtyard tiles — directional hopeful night painting.",
    ),
    "gudi-padwa": (
        "Window nook Gudi: silk scarf drape, inverted brass pot with mango-leaf crown catching morning shaft — crisp watercolor New Year.",
        "Lane perspective with households raising colorful gudis along balconies — festive gouache street tapestry.",
        "Geometric Gudi icon repeated as wallpaper border around blush sunrise void — Marathi graphic charm.",
        "Neighborhood temple dome peek between neem branches sprinkled with flower shower — tender procession freeze.",
        "Sugar-cane stalks crossed behind brass plate with puran poli stack — harvest sweetness still life.",
    ),
    "gujarati-new-year": (
        "Desk vignette: fresh ledger book ribbon marker, rose atop calculator, small bowl shrikhand — business-home watercolor blessing.",
        "Stock-exchange ticker suggested as soft LED blur beyond garlanded window — modern-traditional gouache fusion.",
        "Calendar page flipping abstraction with toran overlay corners — flat temporal hopeful graphic.",
        "Family shop shutter half-open spewing marigold tumble — entrepreneurial sentimental dawn.",
        "Handwritten Gujarati script decorative curls framing empty parchment tone center — cultural pride border.",
    ),
    "guru-nanak-jayanti": (
        "Golden Temple reflected as elongated gold brushstroke on sarovar watercolor wash — reverent architecture dawn.",
        "Nagar kirtan distant: saffron flags as rhythm stripes, harmonium shape lump — wide procession gouache.",
        "Ik Onkar motif halo with khanda accents framing muted amber interior — sacred typography illustration.",
        "Langar hall steam tables suggested by parallel warmth bands, volunteer silhouettes — communal softness painterly.",
        "Guru Nanak stylized miniature seated posture amid manuscripts and lotus — lithograph warmth NOT photo skin.",
    ),
    "hanuman-jayanti": (
        "Mountain-backed shrine shelf with sindoor mound, brass gada ornament, marigold waterfall — heroic watercolor shrine vignette.",
        "Hanuman leap silhouette as orange watercolor smudge across teal sky with pearl moon — myth kinetic softness.",
        "Repeating mountain-and-tail motif border around glowing apricot core — graphic Bajrang devotion.",
        "Ram naam folded tulsi leaf offering beside miniature mountains sugar sculpture — tender anecdotal still life.",
        "Dawn ridge prayer flags as tiny orange punctuation marks against cooling sky — playful restrained devotion.",
    ),
    "halloween": (
        "Pumpkin trio grin patterns staggered on porch steps, cobweb gauze, moth circling porch bulb — cozy spooky watercolor.",
        "Harvest moon behind skeletal tree silhouette, candy corn scatter trail leading inward — wide gouache kids-safe.",
        "Bat-and-star tessellation border around smoky lilac center — cartoon Gothic-lite graphic.",
        "Cauldron steam forming ghost doodles above apple bob basin — humorous pastel suspense.",
        "Black cat curve intersecting witch hat cone as minimal logo-like playful flat — stylish restraint.",
    ),
    "holi": (
        "Powder explosion freeze: magenta and turmeric clouds crossing mid-air above brass glasses — energetic watercolor burst.",
        "Courtyard bucket pyramid with soaked pichkaris draped, rainbow drips on whitewash — wide aftermath gouache humor.",
        "Paisley splash symmetry mandala from pigment splats — abstract festive graphic core.",
        "Wrapped glasses of thandai with pistachio dust heart — refreshing macro sentimental.",
        "White kurta becoming galaxy of pigment flecks close macro — transformation joy painterly.",
    ),
    "independence-day": (
        "Silk tricolor crumpled sculpturally with stitched chakra applique catching beam — tactile patriotic watercolor.",
        "School grounds tiny aligned flags diminishing perspective toward podium microphone silhouette — communal gouache pride.",
        "Ashoka chakra gear motif radiating line bursts border around pearl gray calm — geometric solemn graphic.",
        "Kite strings crossing sunset orange slice with paper kite diamonds — playful freedom metaphor painterly.",
        "Freedom fighter silhouette monument softened into lavender dusk fog — historic sentimental breadth.",
    ),
    "janmashtami": (
        "Flower hammock swing heavy with jasmine ropes against midnight blue speckle — cradle watercolor anticipation.",
        "Krishna butter-hand motif clay plaques stacked beside spill-pattern yogurt swirl — playful miniature narrative.",
        "Matki pyramid with reachable pot cracked glow suggesting prize — festive tiered gouache energy.",
        "Baby Krishna stylized miniature crawling toward overturned butter pot — calendar-soft NOT doll-photo.",
        "Courtyard raas circles suggested by dupatta color arcs blurred motion — joyful rotational abstraction.",
    ),
    "just-because": (
        "Impulse bouquet wrapped in brown paper on bench beside steaming chai — spontaneous watercolor kindness.",
        "Letter tucked under windshield wiper with heart sticker catching drizzle jewel — urban gouache gentle surprise.",
        "Floating envelopes raining pastel parachutes border framing cloudy affection center — whimsical graphic.",
        "Park ducks vague shapes receiving crumb toss arm silhouette — everyday tenderness painterly.",
        "Night fridge glow illuminating leftover cake slice on floral plate — cozy mundane romance.",
    ),
    "karva-chauth": (
        "Brass sieve concentric rings framing pastel moon disk rising above terrace parapet — ritual watercolor intimacy.",
        "Mehndi drying cones beside lace dupatta fold and stacked sweets — bridal-night gouache glow.",
        "Moon-through-jali lattice shadow cast on cushion pile — patterned sentimental geometry.",
        "Star-chart faint arcs linking moon to earthen pot silhouette — cosmic fasting metaphor illustration.",
        "Reflection scene: woman silhouette merged with moon ripple in brass water bowl — stylized NO facial detail.",
    ),
    "lohri": (
        "Bonfire core as watercolor donut of ember strands, peanuts scattered foreground circle — winter warmth focal.",
        "Punjabi courtyard drumheads leaning, revdi piles catching sparks — wide festive gouache chill contrast.",
        "Phulkari diamond repeats framing fiery orange heart — folk graphic celebration.",
        "Sugarcane crosses forming protective X behind woven basket — harvest emblem still life.",
        "Baby-celebration implication with folded quilts stack and tiny jaggery cubes — tender family sentimental.",
    ),
    "mahashivratri": (
        "Night lingam-shaped abstract brass forms softened with bilva leaf necklace draped — devotional watercolor blur sacred.",
        "Shiva stylized miniature seated on tiger skin suggestion amid galaxy swirl background — cosmic lithograph calm.",
        "Trident motif rising between twin flame cones symmetrical — iconic flat poster serenity.",
        "Forest temple stairs dew-glistening upward into moonbeam cone — pilgrim mood gouache NO crowds detail.",
        "Nandi silhouette loaf shape foreground framing distant temple lamp constellation — gentle guardian framing.",
    ),
    "makar-sankranti": (
        "Terrace kite reel tangle close-up with mango pickle jar lid reflective — competitive watercolor sky sport.",
        "Sky crowded with geometric kites like stained glass shards above sesame ladoos plate — wide saturated gouache.",
        "Sun transition motif half winter gray half saffron split circle border — seasonal pivot graphic.",
        "Cow silhouette distant pulling sugarcane cart decoration blur — rural sentimental warmth painterly.",
        "Steam spiral from sesame-jaggery tilt pan crossing kite-tail swoosh abstract intersection — motion fusion.",
    ),
    "miss-you": (
        "Twin chai cups one fuller steam swirl directional pointing window rail — longing tabletop watercolor.",
        "Train platform bench empty with folded shawl and ticket stub flutter — departure gouache ache.",
        "Postal stamps collage border around faded handwriting texture blank oval — epistolary graphic nostalgia.",
        "Moon halves mirrored across sea horizon implying distance mathematics — poetic sentimental landscape.",
        "Smartphone face-down beside handwritten recipe card smudge — modern-traditional separation tenderness.",
    ),
    "mothers-day": (
        "Rolling pin mid-roll dust plume frozen, jasmine garland draped mixer bowl edge — kitchen watercolor gratitude.",
        "Garden arbor framing empty rocking chair with knitting lump — maternal absence-presence gouache.",
        "Repeating spice-box lattice border around rose quartz glow center — domestic mandala graphic.",
        "Mehndi-inspired floral vine spelling vague MOM motif disguised elegant — subtle lettering abstraction.",
        "Sunrise breakfast tray with toast heart jam fill unseen hands shadow only — tender silhouette care.",
    ),
    "navratri": (
        "Garba circle footprint smudges on dusted ground, dandiya sticks X foreground — kinetic watercolor evening.",
        "Durga silhouette stylized miniature framed by lion profile curves — divine feminine lithograph dignity.",
        "Mirror-work chaniya choli fold explosion macro glitter softened — textile celebration gouache glamour.",
        "Nine-night lamp countdown painted as ascending flame staircase — conceptual devotional graphic.",
        "Temple acoustic shells suggesting conch chorus layered translucent — sonic abstraction painterly.",
    ),
    "new-year": (
        "Champagne coupe pyramid collapsed into watercolor drip sparkle cascade — midnight countdown glamour softened.",
        "City skyline fireworks as pastel cauliflower blooms mirrored river — wide hopeful gouache panorama.",
        "Clock midnight fragments morphing into dove silhouettes border — temporal transition graphic.",
        "Polaroid-string laundry line of blank yearly memories fluttering — sentimental meta narrative painterly.",
        "Notebook fresh page curl lifting revealing faint fireworks bleed-through — literary new chapter abstraction.",
    ),
    "onam": (
        "Pookalam flower carpet photographed-from-above illusion simplified into painterly rings surrounding banana leaf sadhya hints — Kerala watercolor feast geometry.",
        "Backwater snake-boat prow slicing emerald ripple with umbrella-canopy rhythm — wide gouache race adrenaline softened.",
        "Mahabali folklore tiger-mask motif decorative corners framing emerald gradient — myth graphic restraint.",
        "Banana leaf thali compartments painted mini pickles pyramid payasam copper dot — culinary devotional macro.",
        "Kathakali eyeshadow swoosh abstraction feather arcs complementary greens — cultural flourish illustrative.",
    ),
    "pongal": (
        "Clay pot boil-over cascade catching turmeric streak sunshine across kolam threshold — Tamil harvest watercolor.",
        "Sugarcane tripod framing steaming pongal mound sprinkled moong dal jewels — rustic gouache altar tabletop.",
        "Sun-chariot stylized wheel motifs circling pale dawn oval — cosmic agrarian graphic.",
        "Ox-cart blurred ornament hauling cane bundles silhouette sunrise — pastoral sentimental breadth painterly.",
        "Cow parsley crown doodle hovering above brass bowls symmetry — playful auspicious whimsy illustration.",
    ),
    "raksha-bandhan": (
        "Rakhi threads coiled like miniature bracelets atop crushed velvet with ladoos pyramid — sibling watercolor intimacy.",
        "Child wrist elevation blurred tying knot motion arcs pastel ribbons — medium gouache ceremony tenderness.",
        "Quatrefoil rakhi motif tiling border around rose fog interior — ornate graphic affection.",
        "Satellite dish sentimental implying siblings continents linked by thread beam curvature abstraction — modern diaspora painterly.",
        "Vintage postage rakhi envelope wax seal heart imprint macro — epistolary bond nostalgia.",
    ),
    "ram-navami": (
        "Panaka juice pitchers beaded condensation roses cucumber floats tabletop feast — cooling watercolor festival.",
        "Infant Rama stylized miniature on cradle silk amidst jasmine avalanche — devotional lithograph softness.",
        "Procession tiny Rath silhouette distant ivory tusks decorative blur ONLY geometric beasts — restrained symbolic breadth gouache.",
        "Sugar crystals sparkling pyramid beside tulsi leaf offering bowl macro — sweetness sacramental still life.",
        "Bow motif ornate curled framing midday turquoise halo emptiness — archery virtue abstraction graphic.",
    ),
    "rath-yatra": (
        "Chariot wheel carving macro teal pigment catching procession flower drizzle — tactile watercolor pilgrimage.",
        "Crowd wave abstraction saffron crest surf toward towering chariot silhouette — energetic gouache uplift.",
        "Concentric chakra rangoli with rope-pull motif spikes — geometric ritual graphic.",
        "Beach sand flattened footprints circling toy chariot left by children — playful scaled-down sentimental painterly.",
        "Rain-soaked petals adhering to wheel spokes close macro melancholy joy — weather devotional texture.",
    ),
    "sympathy": (
        "White flowers loose bouquet ribbon undone pooling marble cool tone — grief watercolor restraint.",
        "Empty chair shawl draped rain streak window merge — absence gouache tenderness.",
        "Candle trio melting uneven wax tears symmetrical arrangement — memorial still life graphic-soft.",
        "Misty pier disappearing into fog footsteps fading — existential landscape gentle.",
        "Single dove feather crossing folded prayer hands silhouette charcoal fade — spiritual consolation abstraction.",
    ),
    "thank-you": (
        "Brass diya beside handwritten thank-you stack tied twine jasmine necklace — gratitude watercolor clarity.",
        "Doorstep surprise basket fruit ribbon neighbor kindness — wide porch gouache sunshine.",
        "Floral laurel heart wreath line-art border hugging powder blue calm — appreciation graphic simplicity.",
        "Teacup duo clink ring ripple overhead view abstract gratitude ripple physics — whimsical macro sentimental.",
        "Sunbeam illuminating dust revealing floating pollen Thank-you shaped negative space subtle — ephemeral gratitude painterly.",
    ),
    "thanksgiving": (
        "Cornucopia horn overflowing gourds grapes wheat shafts watercolor crunch texture — harvest tabletop classic.",
        "Farm table distant windows amber leaf-filtered light empty chairs awaiting — wide gouache reunion anticipation.",
        "Turkey feather geometry tessellation border pumpkin spice gradient core — folk-modern graphic.",
        "Pie lattice macro weaving steam vent hearts disguised — cozy culinary sentimental macro.",
        "Family silhouette toast collision glasses starburst highlight ONLY outlines — communal warmth abstraction painterly.",
    ),
    "thinking-of-you": (
        "Open postcard flutter pinned world-map corkboard warm bulb cone — distance watercolor thoughtfulness.",
        "Bench overlooking fog valley telephone cord looping heart loosely unintentional — mood gouache longing.",
        "Thought bubble filled with miniature flower bouquets collage border — whimsical cognitive affection graphic.",
        "Night sky constellations connected dotted line spelling vague initials subtle — cosmic sentimental painterly.",
        "Steam heart morphing from kettle spout toward empty chair knit blanket — domestic phantom hug abstraction.",
    ),
    "valentines": (
        "Rose bouquet browning edges romantic realism watercolor softened velvet ribbon — mature love still life.",
        "Gondola-less canal bridge arch framing two shadows merging pastel — European-Indian fusion gouache date mood.",
        "Victorian lace heart doily border trapping blush fog center — vintage graphic romance.",
        "Champagne cork mid-pop frozen botanical illustration cross-section aesthetic — celebratory quirky macro sentimental.",
        "Mithai heart ladoos stacked skewer like kabob playful spice dust — desi Valentine whimsy painterly.",
    ),
    "vasant-panchami": (
        "Mustard field impressionist yellow brush tornado under cobalt wedge sky — spring watercolor surge.",
        "Veena instrument reclining on silk beside stacked alphabet primers browning edges — learning goddess gouache homage.",
        "Bamboo flute notch macro splitting sunlight spectrum delicate — musical breath abstraction graphic.",
        "Kite duel pastel crossed tails scribbling heart accidental — playful seasonal metaphor painterly.",
        "School slate chalk goddess geometry doodle smudge fingers — childhood Saraswati whisper abstraction.",
    ),
    "welcome": (
        "Rangoli powder jars lids open spectrum arc interrupted center emptiness — inviting watercolor threshold.",
        "Gate folding open flower shower motion blur particles — generous gouache arrival spectacle softened.",
        "Toran repetition arch motifs stacking perspective tunnel toward glowing doorway — graphic depth welcome.",
        "Pair slippers neatly angled outward facing visitor sunbeam — humble hospitality still life sentimental.",
        "Teapot steam shaping doorway arch fantasy inviting silhouette — whimsical chai warmth abstraction painterly.",
    ),
}
