import type { CardTemplate } from "../types";

export const ANNIVERSARY_TEMPLATES: CardTemplate[] = [
  {
    id: "anniversary-01",
    categoryId: "anniversary",
    name: "Timeless Love",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💕", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "❤️", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌹", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💖", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-02",
    categoryId: "anniversary",
    name: "Golden Years",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💛", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "anniversary-03",
    categoryId: "anniversary",
    name: "Sunset Romance",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌅", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "💞", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-04",
    categoryId: "anniversary",
    name: "Cherished Memory",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💝", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "anniversary-05",
    categoryId: "anniversary",
    name: "Love Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "anniversary-06",
    categoryId: "anniversary",
    name: "Starburst Hearts",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "❤️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "💕", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-07",
    categoryId: "anniversary",
    name: "Elegant Anniversary",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💍", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "shimmer" }],
  },
  {
    id: "anniversary-08",
    categoryId: "anniversary",
    name: "Love Letter",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💌", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-09",
    categoryId: "anniversary",
    name: "Rose Garden",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💕", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "❤️", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-10",
    categoryId: "anniversary",
    name: "Heart Garland",
    layout: "garland",
    themeId: "peach",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "❤️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💕", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💖", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💝", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "anniversary-11",
    categoryId: "anniversary",
    name: "Midnight Romance",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "✨", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "anniversary-12",
    categoryId: "anniversary",
    name: "Sky Romance",
    layout: "banner-top",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌤️", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💙", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "anniversary-13",
    categoryId: "anniversary",
    name: "Emerald Elegance",
    layout: "framed",
    themeId: "emerald",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💚", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌿", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "anniversary-14",
    categoryId: "anniversary",
    name: "Violet Dream",
    layout: "starburst",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "anniversary-15",
    categoryId: "anniversary",
    name: "Mint Anniversary",
    layout: "ribbon",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💚", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌿", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "anniversary-16",
    categoryId: "anniversary",
    name: "Sunshine Love",
    layout: "scattered",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "spin-slow" },
      { emoji: "💛", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌻", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "anniversary-17",
    categoryId: "anniversary",
    name: "Lavender Kiss",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💋", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "anniversary-18",
    categoryId: "anniversary",
    name: "Sweet Envelope",
    layout: "envelope",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💗", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌹", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "anniversary-19",
    categoryId: "anniversary",
    name: "Warm Anniversary",
    layout: "garland",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💛", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "anniversary-20",
    categoryId: "anniversary",
    name: "Pure Love",
    layout: "minimal-serif",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "❤️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
];
