import type { CardTemplate } from "../types";

export const BIRTHDAY_TEMPLATES: CardTemplate[] = [
  {
    id: "birthday-01",
    categoryId: "birthday",
    name: "Balloon Bash",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎈",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "🎈",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎂",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎊",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "carnival",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎁",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "carnival",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "birthday-02",
    categoryId: "birthday",
    name: "Cake Day",
    layout: "framed",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎂",
        positionClass: "top-2 left-2",
        sizeClass: "text-6xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎈",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "float",
        animationDelay: "0.3s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.9s",
      },
    ],
  },
  {
    id: "birthday-03",
    categoryId: "birthday",
    name: "Festive Banner",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "💫",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "birthday-04",
    categoryId: "birthday",
    name: "Party Polaroid",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎁",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      { emoji: "🎈", positionClass: "top-1 left-1", sizeClass: "text-4xl", animation: "float", animationDelay: "0.3s" },
      {
        emoji: "🎉",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "pop",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "birthday-05",
    categoryId: "birthday",
    name: "Birthday Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎂",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎈",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎀",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎀",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "birthday-06",
    categoryId: "birthday",
    name: "Star Burst Celebration",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "✨",
        positionClass: "top-1 left-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0.5s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "1s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🎆",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "firework-burst",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "birthday-07",
    categoryId: "birthday",
    name: "Elegant Birthday",
    layout: "minimal-serif",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🌸",
        positionClass: "top-3 right-3",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-3 left-3",
        sizeClass: "text-4xl",
        animation: "twinkle",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "birthday-08",
    categoryId: "birthday",
    name: "Birthday Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.5s",
      },
      {
        emoji: "🎈",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "float",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "birthday-09",
    categoryId: "birthday",
    name: "Scattered Confetti",
    layout: "scattered",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    particlePreset: "confetti-rain",
    ornaments: [
      { emoji: "🎈", positionClass: "top-1 left-1", sizeClass: "text-6xl", animation: "float", animationDelay: "0s" },
      {
        emoji: "🎂",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0.3s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.9s",
      },
      {
        emoji: "🎊",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "jiggle",
        animationDelay: "1.2s",
      },
      {
        emoji: "⭐",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "birthday-10",
    categoryId: "birthday",
    name: "Birthday Garland",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎂",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
      { emoji: "🎈", positionClass: "top-0 left-0", sizeClass: "text-3xl", animation: "float", animationDelay: "0.2s" },
      {
        emoji: "🎉",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "jiggle",
        animationDelay: "0.4s",
      },
      { emoji: "🎁", positionClass: "top-0 left-0", sizeClass: "text-3xl", animation: "pop", animationDelay: "0.6s" },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "twinkle",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "birthday-11",
    categoryId: "birthday",
    name: "Midnight Birthday",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "✨",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "spin-grow",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "firework-burst",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "birthday-12",
    categoryId: "birthday",
    name: "Pink Balloon Party",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎈",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "🎈",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎀",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "pendulum",
        animationDelay: "0.3s",
      },
      {
        emoji: "🎀",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "pendulum",
        animationDelay: "0.9s",
      },
    ],
  },
  {
    id: "birthday-13",
    categoryId: "birthday",
    name: "Golden Celebration",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "🏆",
        positionClass: "top-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "🥇",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "0.7s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "rainbow-burst",
        animationDelay: "0.2s",
      },
    ],
  },
  {
    id: "birthday-14",
    categoryId: "birthday",
    name: "Rainbow Party",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🌈",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎉",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎈",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "1.2s",
      },
      {
        emoji: "🎁",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "jiggle",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "birthday-15",
    categoryId: "birthday",
    name: "Purple Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "💜",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.5s",
      },
      {
        emoji: "✨",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "birthday-16",
    categoryId: "birthday",
    name: "Sunny Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "☀️",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "wobbly-spin",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
      {
        emoji: "💛",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "birthday-17",
    categoryId: "birthday",
    name: "Mint Garland",
    layout: "garland",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎂",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
      { emoji: "🌿", positionClass: "top-0 left-0", sizeClass: "text-3xl", animation: "sway", animationDelay: "0.2s" },
      {
        emoji: "🎉",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "jiggle",
        animationDelay: "0.4s",
      },
      {
        emoji: "🍀",
        positionClass: "top-0 left-0",
        sizeClass: "text-3xl",
        animation: "wobbly-spin",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "birthday-18",
    categoryId: "birthday",
    name: "Rose Polaroid",
    layout: "polaroid",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🌹",
        positionClass: "top-1 left-1",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0s",
      },
      {
        emoji: "💖",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "birthday-19",
    categoryId: "birthday",
    name: "Lavender Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "💜",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "float",
        animationDelay: "0s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌸",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "lotus-bloom",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "birthday-20",
    categoryId: "birthday",
    name: "Classic Birthday",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎂",
        positionClass: "top-3 right-3",
        sizeClass: "text-5xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
    ],
  },
];
