import type { CardTemplate } from "../types";

export const BIRTHDAY_TEMPLATES: CardTemplate[] = [
  {
    id: "birthday-01",
    categoryId: "birthday",
    name: "Balloon Bash",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🎈", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🎂", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🎉", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🎁", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "birthday-02",
    categoryId: "birthday",
    name: "Cake Day",
    layout: "framed",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎂", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎈", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "birthday-03",
    categoryId: "birthday",
    name: "Festive Banner",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎉", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-04",
    categoryId: "birthday",
    name: "Party Polaroid",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🎁", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "birthday-05",
    categoryId: "birthday",
    name: "Birthday Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎂", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎈", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "birthday-06",
    categoryId: "birthday",
    name: "Star Burst Celebration",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-07",
    categoryId: "birthday",
    name: "Elegant Birthday",
    layout: "minimal-serif",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
  {
    id: "birthday-08",
    categoryId: "birthday",
    name: "Birthday Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎉", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "🎁", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "birthday-09",
    categoryId: "birthday",
    name: "Scattered Confetti",
    layout: "scattered",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎈", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🎂", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🎉", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🎁", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "birthday-10",
    categoryId: "birthday",
    name: "Birthday Garland",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎂", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎈", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎉", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎁", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "birthday-11",
    categoryId: "birthday",
    name: "Midnight Birthday",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-12",
    categoryId: "birthday",
    name: "Pink Balloon",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎈", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🎈", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "birthday-13",
    categoryId: "birthday",
    name: "Golden Celebration",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🏆", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-14",
    categoryId: "birthday",
    name: "Rainbow Party",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🌈", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "shimmer" },
      { emoji: "🎉", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🎊", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🎈", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "birthday-15",
    categoryId: "birthday",
    name: "Purple Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎁", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "birthday-16",
    categoryId: "birthday",
    name: "Sunny Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-17",
    categoryId: "birthday",
    name: "Mint Garland",
    layout: "garland",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎂", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌿", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎉", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍀", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "birthday-18",
    categoryId: "birthday",
    name: "Rose Polaroid",
    layout: "polaroid",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "birthday-19",
    categoryId: "birthday",
    name: "Lavender Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "✨", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "birthday-20",
    categoryId: "birthday",
    name: "Classic Birthday",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🎂", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
