import type { CardTemplate } from "../types";

export const CHRISTMAS_TEMPLATES: CardTemplate[] = [
  {
    id: "christmas-01",
    categoryId: "christmas",
    name: "Merry Christmas",
    layout: "centered-stack",
    themeId: "christmas-red",
    primaryAnimation: "fade-in",
    particlePreset: "snow",
    ornaments: [
      {
        emoji: "🎄",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "⛄",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
      {
        emoji: "🎅",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "carnival",
        animationDelay: "1s",
      },
    ],
  },
  {
    id: "christmas-02",
    categoryId: "christmas",
    name: "Santa's Surprise",
    layout: "banner-top",
    themeId: "christmas-red",
    primaryAnimation: "drop-in",
    particlePreset: "snow",
    ornaments: [
      {
        emoji: "🎅",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "❄️",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "wobbly-spin",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "christmas-03",
    categoryId: "christmas",
    name: "Holiday Starburst",
    layout: "starburst",
    themeId: "emerald",
    primaryAnimation: "shimmer",
    particlePreset: "snow",
    ornaments: [
      {
        emoji: "⭐",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🎄",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.4s",
      },
      {
        emoji: "❄️",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎁",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.7s",
      },
      {
        emoji: "🔔",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "1s",
      },
    ],
  },
  {
    id: "christmas-04",
    categoryId: "christmas",
    name: "Winter Wonderland",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    particlePreset: "snow",
    ornaments: [
      {
        emoji: "❄️",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "wobbly-spin",
        animationDelay: "0s",
      },
      {
        emoji: "⛄",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.5s",
      },
      {
        emoji: "🌨️",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "float",
        animationDelay: "0.3s",
      },
      {
        emoji: "🎿",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.7s",
      },
      {
        emoji: "❄️",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "christmas-05",
    categoryId: "christmas",
    name: "Christmas Garland",
    layout: "garland",
    themeId: "christmas-red",
    primaryAnimation: "rise",
    particlePreset: "snow",
    ornaments: [
      {
        emoji: "🎄",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎁",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "elastic-pop",
        animationDelay: "0.4s",
      },
      {
        emoji: "❄️",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "wobbly-spin",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎄",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "bounce-gentle",
        animationDelay: "0.8s",
      },
    ],
  },
];
