import type { CardTemplate } from "../types";

export const CONGRATS_TEMPLATES: CardTemplate[] = [
  {
    id: "congrats-01",
    categoryId: "congrats",
    name: "Big Congrats",
    layout: "centered-stack",
    themeId: "sunshine",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🏆",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.8s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🥳",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "rubber-shake",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "congrats-02",
    categoryId: "congrats",
    name: "Golden Trophy",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🏆",
        positionClass: "top-2 left-2",
        sizeClass: "text-6xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
      {
        emoji: "🥇",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "0.8s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "rainbow-burst",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "congrats-03",
    categoryId: "congrats",
    name: "Achievement Banner",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
      {
        emoji: "🏆",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "congrats-04",
    categoryId: "congrats",
    name: "Congrats Polaroid",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎊",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "congrats-05",
    categoryId: "congrats",
    name: "Champion Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "🥇",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
      {
        emoji: "🏆",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "congrats-06",
    categoryId: "congrats",
    name: "Starburst Win",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "bounce-gentle",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "⭐",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "spin-grow",
        animationDelay: "0.8s",
      },
      {
        emoji: "🏆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.2s",
      },
    ],
  },
  {
    id: "congrats-07",
    categoryId: "congrats",
    name: "Elegant Congrats",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎖️",
        positionClass: "top-3 right-3",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
    ],
  },
  {
    id: "congrats-08",
    categoryId: "congrats",
    name: "Congrats Envelope",
    layout: "envelope",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🏆",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.5s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "congrats-09",
    categoryId: "congrats",
    name: "Victory Scatter",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🎊",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.4s",
      },
      {
        emoji: "🏆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.8s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🥳",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "rubber-shake",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "congrats-10",
    categoryId: "congrats",
    name: "Trophy Garland",
    layout: "garland",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🏆",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎉",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "elastic-pop",
        animationDelay: "0.4s",
      },
      {
        emoji: "🥇",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "rainbow-burst",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎊",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "carnival",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "congrats-11",
    categoryId: "congrats",
    name: "Midnight Win",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "✨",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "spin-grow",
        animationDelay: "0.2s",
      },
      {
        emoji: "🏆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "congrats-12",
    categoryId: "congrats",
    name: "Emerald Achievement",
    layout: "framed",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-5xl", animation: "sway", animationDelay: "0s" },
      {
        emoji: "🎖️",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.4s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "congrats-13",
    categoryId: "congrats",
    name: "Rose Banner",
    layout: "banner-top",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🌹",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "float",
        animationDelay: "0s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "congrats-14",
    categoryId: "congrats",
    name: "Lavender Congrats",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "💜",
        positionClass: "top-1 left-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🌸",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "lotus-bloom",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "congrats-15",
    categoryId: "congrats",
    name: "Violet Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "💜",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "congrats-16",
    categoryId: "congrats",
    name: "Mint Scatter",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-1 left-1", sizeClass: "text-5xl", animation: "sway", animationDelay: "0s" },
      {
        emoji: "🍀",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.4s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "rainbow-burst",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "congrats-17",
    categoryId: "congrats",
    name: "Sunshine Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "☀️",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "wobbly-spin",
        animationDelay: "0s",
      },
      {
        emoji: "💛",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.4s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "congrats-18",
    categoryId: "congrats",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🧡",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "congrats-19",
    categoryId: "congrats",
    name: "Peach Garland",
    layout: "garland",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎉",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🧡",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "zoom-pulse",
        animationDelay: "0.2s",
      },
      {
        emoji: "🏆",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "rainbow-burst",
        animationDelay: "0.4s",
      },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "congrats-20",
    categoryId: "congrats",
    name: "Pure Congrats",
    layout: "minimal-serif",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🎖️",
        positionClass: "top-3 right-3",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
    ],
  },
];
