import type { CardTemplate } from "../types";

export const CONGRATS_TEMPLATES: CardTemplate[] = [
  {
    id: "congrats-01",
    categoryId: "congrats",
    name: "Big Congrats",
    layout: "centered-stack",
    themeId: "sunshine",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🎉", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🏆", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "shimmer" },
      { emoji: "🎊", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-02",
    categoryId: "congrats",
    name: "Golden Trophy",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🏆", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-03",
    categoryId: "congrats",
    name: "Achievement Banner",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎉", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-04",
    categoryId: "congrats",
    name: "Congrats Polaroid",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🎊", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" }],
  },
  {
    id: "congrats-05",
    categoryId: "congrats",
    name: "Champion Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🥇", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "🎊", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "congrats-06",
    categoryId: "congrats",
    name: "Starburst Win",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "⭐", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-07",
    categoryId: "congrats",
    name: "Elegant Congrats",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🎖️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "shimmer" }],
  },
  {
    id: "congrats-08",
    categoryId: "congrats",
    name: "Congrats Envelope",
    layout: "envelope",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎉", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "🏆", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "congrats-09",
    categoryId: "congrats",
    name: "Victory Scatter",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🎉", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🎊", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🏆", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "shimmer" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-10",
    categoryId: "congrats",
    name: "Trophy Garland",
    layout: "garland",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🏆", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎉", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🥇", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎊", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "congrats-11",
    categoryId: "congrats",
    name: "Midnight Win",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-12",
    categoryId: "congrats",
    name: "Emerald Achievement",
    layout: "framed",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🎖️", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "congrats-13",
    categoryId: "congrats",
    name: "Rose Banner",
    layout: "banner-top",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🎉", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "congrats-14",
    categoryId: "congrats",
    name: "Lavender Congrats",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "congrats-15",
    categoryId: "congrats",
    name: "Violet Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎊", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "congrats-16",
    categoryId: "congrats",
    name: "Mint Scatter",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍀", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "⭐", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "congrats-17",
    categoryId: "congrats",
    name: "Sunshine Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "💛", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "congrats-18",
    categoryId: "congrats",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎉", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "congrats-19",
    categoryId: "congrats",
    name: "Peach Garland",
    layout: "garland",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎉", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🧡", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🏆", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "congrats-20",
    categoryId: "congrats",
    name: "Pure Congrats",
    layout: "minimal-serif",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🎖️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "shimmer" }],
  },
];
