import type { CardTemplate } from "../types";

export const DIWALI_TEMPLATES: CardTemplate[] = [
  {
    id: "diwali-01",
    categoryId: "diwali",
    name: "Festival of Lights",
    layout: "centered-stack",
    themeId: "deep-diwali",
    primaryAnimation: "fade-in",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🪔",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "diya-flicker",
        animationDelay: "0s",
      },
      {
        emoji: "🪔",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "diya-flicker",
        animationDelay: "0.4s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
      {
        emoji: "🪔",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "diya-flicker",
        animationDelay: "0.6s",
      },
      {
        emoji: "🪔",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "diya-flicker",
        animationDelay: "1s",
      },
    ],
  },
  {
    id: "diwali-02",
    categoryId: "diwali",
    name: "Golden Rangoli",
    layout: "starburst",
    themeId: "saffron-gold",
    primaryAnimation: "glow-pulse",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🌟",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "spin-grow",
        animationDelay: "0.3s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "spin-grow",
        animationDelay: "0.8s",
      },
      {
        emoji: "🪔",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "diya-flicker",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "diwali-03",
    categoryId: "diwali",
    name: "Diya Garland",
    layout: "garland",
    themeId: "saffron-gold",
    primaryAnimation: "rise",
    particlePreset: "embers",
    ornaments: [
      {
        emoji: "🪔",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "diya-flicker",
        animationDelay: "0s",
      },
      {
        emoji: "✨",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🪔",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "diya-flicker",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌟",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "glow-pulse",
        animationDelay: "0.6s",
      },
      {
        emoji: "🪔",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "diya-flicker",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "diwali-04",
    categoryId: "diwali",
    name: "Fireworks Night",
    layout: "scattered",
    themeId: "deep-diwali",
    primaryAnimation: "shimmer",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎇",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.5s",
      },
      {
        emoji: "💥",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.3s",
      },
      {
        emoji: "🎆",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "firework-burst",
        animationDelay: "1s",
      },
      {
        emoji: "✨",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
      {
        emoji: "🎇",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "firework-burst",
        animationDelay: "1.3s",
      },
    ],
  },
  {
    id: "diwali-05",
    categoryId: "diwali",
    name: "Lakshmi Blessing",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    particlePreset: "embers",
    ornaments: [
      {
        emoji: "🪔",
        positionClass: "top-2 left-2",
        sizeClass: "text-5xl",
        animation: "diya-flicker",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.4s",
      },
      {
        emoji: "🪔",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "diya-flicker",
        animationDelay: "0.8s",
      },
      {
        emoji: "🌺",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "1.2s",
      },
    ],
  },
  {
    id: "diwali-06",
    categoryId: "diwali",
    name: "Midnight Sparkle",
    layout: "banner-top",
    themeId: "marigold",
    primaryAnimation: "wave-in",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🪔",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "diya-flicker",
        animationDelay: "0s",
      },
      {
        emoji: "🪔",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "diya-flicker",
        animationDelay: "0.5s",
      },
      {
        emoji: "🌟",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🌟",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.8s",
      },
    ],
  },
];
