import type { CardTemplate } from "../types";

export const DUSSEHRA_TEMPLATES: CardTemplate[] = [
  {
    id: "dussehra-01",
    categoryId: "dussehra",
    name: "Victory of Good",
    layout: "centered-stack",
    themeId: "festival-crimson",
    primaryAnimation: "glow-pulse",
    ornaments: [
      {
        emoji: "🌟",
        positionClass: "top-2 left-2",
        sizeClass: "text-3xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "✨",
        positionClass: "top-2 right-2",
        sizeClass: "text-3xl",
        animation: "twinkle",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌺",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-2xl",
        animation: "lotus-bloom",
        animationDelay: "0.2s",
      },
      {
        emoji: "🪔",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-2xl",
        animation: "diya-flicker",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "dussehra-02",
    categoryId: "dussehra",
    name: "Vijayadashami",
    layout: "starburst",
    themeId: "saffron-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "🌟",
        positionClass: "top-2 left-2",
        sizeClass: "text-3xl",
        animation: "glow-pulse",
        animationDelay: "0s",
      },
      { emoji: "🎉", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pop", animationDelay: "0.3s" },
      { emoji: "🪔", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "diya-flicker" },
      { emoji: "🌺", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "lotus-bloom" },
    ],
  },
  {
    id: "dussehra-03",
    categoryId: "dussehra",
    name: "Triumph Banner",
    layout: "banner-top",
    themeId: "amber-gold",
    primaryAnimation: "wave-in",
    ornaments: [
      {
        emoji: "🌟",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-3xl",
        animation: "glow-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-3xl",
        animation: "firework-burst",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "dussehra-04",
    categoryId: "dussehra",
    name: "Festive Garland",
    layout: "garland",
    themeId: "festival-crimson",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌟", positionClass: "top-0", sizeClass: "text-xl", animation: "none" },
      { emoji: "🌺", positionClass: "top-0", sizeClass: "text-xl", animation: "none" },
      { emoji: "✨", positionClass: "top-0", sizeClass: "text-xl", animation: "none" },
      { emoji: "🎊", positionClass: "top-0", sizeClass: "text-xl", animation: "none" },
    ],
  },
];
