import type { CardTemplate } from "../types";

export const FATHERS_DAY_TEMPLATES: CardTemplate[] = [
  {
    id: "fathers-day-01",
    categoryId: "fathers-day",
    name: "Classic Dad",
    layout: "centered-stack",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "👔", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "fathers-day-02",
    categoryId: "fathers-day",
    name: "Super Dad",
    layout: "framed",
    themeId: "slate-clean",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🏆", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "fathers-day-03",
    categoryId: "fathers-day",
    name: "Golf Day",
    layout: "banner-top",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "⛳", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🏌️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "fathers-day-04",
    categoryId: "fathers-day",
    name: "Outdoor Dad",
    layout: "starburst",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌲", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🏕️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "fathers-day-05",
    categoryId: "fathers-day",
    name: "Dad's Tie",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [{ emoji: "👔", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" }],
  },
  {
    id: "fathers-day-06",
    categoryId: "fathers-day",
    name: "Best Dad",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🏅", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "shimmer" }],
  },
  {
    id: "fathers-day-07",
    categoryId: "fathers-day",
    name: "World's Greatest",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌍", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "spin-slow" }],
  },
  {
    id: "fathers-day-08",
    categoryId: "fathers-day",
    name: "Dad's Workshop",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🔧", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🔨", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "fathers-day-09",
    categoryId: "fathers-day",
    name: "BBQ King",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🔥", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🍖", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "👑", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "shimmer" },
    ],
  },
  {
    id: "fathers-day-10",
    categoryId: "fathers-day",
    name: "Sports Fan",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "⚽", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🏈", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🏆", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "fathers-day-11",
    categoryId: "fathers-day",
    name: "Midnight Hero",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "fathers-day-12",
    categoryId: "fathers-day",
    name: "Fishing Trip",
    layout: "banner-top",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🎣", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🐟", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "fathers-day-13",
    categoryId: "fathers-day",
    name: "Golden Dad",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🏆", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "👑", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "fathers-day-14",
    categoryId: "fathers-day",
    name: "Dad Jokes",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "😄", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "🎭", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "fathers-day-15",
    categoryId: "fathers-day",
    name: "Road Trip Dad",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🚗", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🗺️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "fathers-day-16",
    categoryId: "fathers-day",
    name: "Reading Dad",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "📚", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "fathers-day-17",
    categoryId: "fathers-day",
    name: "Music Dad",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎵", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🎸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "fathers-day-18",
    categoryId: "fathers-day",
    name: "Tea & Relaxation",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "☕", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
  {
    id: "fathers-day-19",
    categoryId: "fathers-day",
    name: "Navy Blue",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "⚓", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🚢", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "fathers-day-20",
    categoryId: "fathers-day",
    name: "Simple & Sincere",
    layout: "envelope",
    themeId: "slate-clean",
    primaryAnimation: "rise",
    ornaments: [{ emoji: "💙", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
];
