import type { CardTemplate } from "../types";

export const GANESH_CHATURTHI_TEMPLATES: CardTemplate[] = [
  {
    id: "ganesh-chaturthi-01",
    categoryId: "ganesh-chaturthi",
    name: "Ganpati Bappa",
    layout: "centered-stack",
    themeId: "saffron-gold",
    primaryAnimation: "glow-pulse",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "🐘",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.5s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🌸",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.8s",
      },
      {
        emoji: "🪷",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "ganesh-chaturthi-02",
    categoryId: "ganesh-chaturthi",
    name: "Modak Blessings",
    layout: "framed",
    themeId: "marigold",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🐘",
        positionClass: "top-2 left-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "glow-pulse",
        animationDelay: "0.7s",
      },
      {
        emoji: "🪷",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.2s",
      },
    ],
  },
  {
    id: "ganesh-chaturthi-03",
    categoryId: "ganesh-chaturthi",
    name: "Floral Garland",
    layout: "garland",
    themeId: "saffron-gold",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🐘",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "lotus-bloom",
        animationDelay: "0.2s",
      },
      {
        emoji: "✨",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌸",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "lotus-bloom",
        animationDelay: "0.6s",
      },
      {
        emoji: "🐘",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "bounce-gentle",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "ganesh-chaturthi-04",
    categoryId: "ganesh-chaturthi",
    name: "Golden Elephant",
    layout: "starburst",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🐘",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🪷",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.5s",
      },
      {
        emoji: "🌟",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🌺",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.8s",
      },
      {
        emoji: "✨",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "1.1s",
      },
    ],
  },
];
