import type { CardTemplate } from "../types";

export const GET_WELL_TEMPLATES: CardTemplate[] = [
  {
    id: "get-well-01",
    categoryId: "get-well",
    name: "Healing Wishes",
    layout: "centered-stack",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌷", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💚", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "get-well-02",
    categoryId: "get-well",
    name: "Garden Recovery",
    layout: "framed",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🍀", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-03",
    categoryId: "get-well",
    name: "Sunshine Banner",
    layout: "banner-top",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "☀️", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "🌈", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "get-well-04",
    categoryId: "get-well",
    name: "Soft Polaroid",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "get-well-05",
    categoryId: "get-well",
    name: "Rose Ribbon",
    layout: "ribbon",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "get-well-06",
    categoryId: "get-well",
    name: "Healing Starburst",
    layout: "starburst",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌊", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-07",
    categoryId: "get-well",
    name: "Gentle Wishes",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
  {
    id: "get-well-08",
    categoryId: "get-well",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌷", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💛", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "get-well-09",
    categoryId: "get-well",
    name: "Flower Meadow",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍀", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌿", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-10",
    categoryId: "get-well",
    name: "Floral Garland",
    layout: "garland",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "get-well-11",
    categoryId: "get-well",
    name: "Blue Sky Recovery",
    layout: "centered-stack",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌤️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "☁️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-12",
    categoryId: "get-well",
    name: "Tea Time Wishes",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🍵", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "none" }],
  },
  {
    id: "get-well-13",
    categoryId: "get-well",
    name: "Amber Wishes",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌻", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💛", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "get-well-14",
    categoryId: "get-well",
    name: "Lavender Healing",
    layout: "ribbon",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "get-well-15",
    categoryId: "get-well",
    name: "Gentle Starburst",
    layout: "starburst",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌟", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "get-well-16",
    categoryId: "get-well",
    name: "Emerald Garland",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍀", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌱", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "get-well-17",
    categoryId: "get-well",
    name: "Peach Healing",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-18",
    categoryId: "get-well",
    name: "Scattered Blossoms",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "💐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "get-well-19",
    categoryId: "get-well",
    name: "Sunshine Envelope",
    layout: "envelope",
    themeId: "sunshine",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "☀️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "🌈", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "get-well-20",
    categoryId: "get-well",
    name: "Simple Comfort",
    layout: "minimal-serif",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌱", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
