import type { CardTemplate } from "../types";

export const GOOD_LUCK_TEMPLATES: CardTemplate[] = [
  {
    id: "good-luck-01",
    categoryId: "good-luck",
    name: "Lucky Clover",
    layout: "centered-stack",
    themeId: "emerald",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🍀", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-02",
    categoryId: "good-luck",
    name: "Golden Luck",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🍀", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "good-luck-03",
    categoryId: "good-luck",
    name: "Lucky Banner",
    layout: "banner-top",
    themeId: "sunshine",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌟", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🍀", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "good-luck-04",
    categoryId: "good-luck",
    name: "Luck Polaroid",
    layout: "polaroid",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🍀", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" }],
  },
  {
    id: "good-luck-05",
    categoryId: "good-luck",
    name: "Star Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-06",
    categoryId: "good-luck",
    name: "Lucky Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-07",
    categoryId: "good-luck",
    name: "Minimal Luck",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🍀", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "sway" }],
  },
  {
    id: "good-luck-08",
    categoryId: "good-luck",
    name: "Luck Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "⭐", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-09",
    categoryId: "good-luck",
    name: "Star Scatter",
    layout: "scattered",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🍀", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-10",
    categoryId: "good-luck",
    name: "Clover Garland",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌿", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌟", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "good-luck-11",
    categoryId: "good-luck",
    name: "Rose Luck",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-12",
    categoryId: "good-luck",
    name: "Lavender Banner",
    layout: "banner-top",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-13",
    categoryId: "good-luck",
    name: "Peach Luck",
    layout: "framed",
    themeId: "peach",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🧡", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-14",
    categoryId: "good-luck",
    name: "Midnight Star",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-15",
    categoryId: "good-luck",
    name: "Emerald Ribbon",
    layout: "ribbon",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "good-luck-16",
    categoryId: "good-luck",
    name: "Sunshine Luck",
    layout: "starburst",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🍀", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "good-luck-17",
    categoryId: "good-luck",
    name: "Sky Luck",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌤️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "good-luck-18",
    categoryId: "good-luck",
    name: "Warm Garland",
    layout: "garland",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🧡", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌟", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "good-luck-19",
    categoryId: "good-luck",
    name: "Violet Envelope",
    layout: "envelope",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "⭐", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "good-luck-20",
    categoryId: "good-luck",
    name: "Clean Luck",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "⭐", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "twinkle" }],
  },
];
