import type { CardTemplate } from "../types";

export const HALLOWEEN_TEMPLATES: CardTemplate[] = [
  {
    id: "halloween-01",
    categoryId: "halloween",
    name: "Pumpkin Patch",
    layout: "centered-stack",
    themeId: "amber-gold",
    primaryAnimation: "pulse-soft",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "🎃",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "🦇",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.4s",
      },
      {
        emoji: "🕷️",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.2s",
      },
      {
        emoji: "🌙",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.7s",
      },
      {
        emoji: "👻",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "float",
        animationDelay: "1s",
      },
    ],
  },
  {
    id: "halloween-02",
    categoryId: "halloween",
    name: "Haunted House",
    layout: "framed",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "👻", positionClass: "top-2 left-2", sizeClass: "text-6xl", animation: "float", animationDelay: "0s" },
      {
        emoji: "🎃",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.4s",
      },
      {
        emoji: "🦇",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.7s",
      },
      {
        emoji: "🕸️",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "sway",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "halloween-03",
    categoryId: "halloween",
    name: "Friendly Ghost",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "👻",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "👻",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0.6s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "halloween-04",
    categoryId: "halloween",
    name: "Witch's Brew",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "pulse-soft",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "🧙‍♀️",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🌙",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.4s",
      },
      {
        emoji: "🔮",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.8s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
    ],
  },
  {
    id: "halloween-05",
    categoryId: "halloween",
    name: "Spooky Forest",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "sway",
    ornaments: [
      { emoji: "🌲", positionClass: "top-1 left-1", sizeClass: "text-6xl", animation: "sway", animationDelay: "0s" },
      {
        emoji: "🦉",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎃",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.8s",
      },
      {
        emoji: "🦇",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "pendulum",
        animationDelay: "0.2s",
      },
      {
        emoji: "🌙",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "halloween-06",
    categoryId: "halloween",
    name: "Skeleton Dance",
    layout: "ribbon",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "💀",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "🦴",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "jiggle",
        animationDelay: "0.4s",
      },
      { emoji: "👻", positionClass: "top-2 left-2", sizeClass: "text-4xl", animation: "float", animationDelay: "0.7s" },
    ],
  },
  {
    id: "halloween-07",
    categoryId: "halloween",
    name: "Orange Moon",
    layout: "polaroid",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🌕",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "🦇",
        positionClass: "top-1 left-1",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "halloween-08",
    categoryId: "halloween",
    name: "Bat Cave",
    layout: "envelope",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🦇",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🦇",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.6s",
      },
      {
        emoji: "🦇",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "halloween-09",
    categoryId: "halloween",
    name: "Candy Haul",
    layout: "garland",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🍬",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "bounce-gentle",
        animationDelay: "0s",
      },
      {
        emoji: "🍫",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "rubber-shake",
        animationDelay: "0.2s",
      },
      {
        emoji: "🍭",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "wobbly-spin",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎃",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "elastic-pop",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "halloween-10",
    categoryId: "halloween",
    name: "Monster Mash",
    layout: "centered-stack",
    themeId: "violet",
    primaryAnimation: "bounce-gentle",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "🧟",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "👻",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0.4s",
      },
      {
        emoji: "🧛",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎃",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
    ],
  },
  {
    id: "halloween-11",
    categoryId: "halloween",
    name: "Cauldron Magic",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "🫧", positionClass: "top-2 left-2", sizeClass: "text-5xl", animation: "float", animationDelay: "0s" },
      {
        emoji: "🧪",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.4s",
      },
      {
        emoji: "🔮",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "halloween-12",
    categoryId: "halloween",
    name: "Jack-o-Lantern",
    layout: "banner-top",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "🎃",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🕯️",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "diya-flicker",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌙",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "halloween-13",
    categoryId: "halloween",
    name: "Vampire Night",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      {
        emoji: "🧛",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🌙",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.5s",
      },
      {
        emoji: "🦇",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "pendulum",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "halloween-14",
    categoryId: "halloween",
    name: "Spider Web",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🕸️", positionClass: "top-1 left-1", sizeClass: "text-6xl", animation: "sway", animationDelay: "0s" },
      {
        emoji: "🕷️",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.5s",
      },
      {
        emoji: "💀",
        positionClass: "top-1 right-1",
        sizeClass: "text-4xl",
        animation: "rubber-shake",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "halloween-15",
    categoryId: "halloween",
    name: "Autumn Spooky",
    layout: "minimal-serif",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🍂", positionClass: "top-3 right-3", sizeClass: "text-5xl", animation: "float", animationDelay: "0s" },
      {
        emoji: "🍁",
        positionClass: "bottom-3 left-3",
        sizeClass: "text-4xl",
        animation: "sway",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "halloween-16",
    categoryId: "halloween",
    name: "Trick or Treat",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      {
        emoji: "🍬",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "🎃",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.5s",
      },
      { emoji: "👻", positionClass: "top-2 left-2", sizeClass: "text-4xl", animation: "float", animationDelay: "0.3s" },
    ],
  },
  {
    id: "halloween-17",
    categoryId: "halloween",
    name: "Eerie Purple",
    layout: "polaroid",
    themeId: "violet",
    primaryAnimation: "pulse-soft",
    ornaments: [
      {
        emoji: "🔮",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0s",
      },
      {
        emoji: "💜",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "halloween-18",
    categoryId: "halloween",
    name: "Haunted Garland",
    layout: "garland",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "👻", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "float", animationDelay: "0s" },
      {
        emoji: "🎃",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
      {
        emoji: "🦇",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "pendulum",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌙",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "zoom-pulse",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "halloween-19",
    categoryId: "halloween",
    name: "Cozy Halloween",
    layout: "envelope",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🕯️",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "diya-flicker",
        animationDelay: "0s",
      },
      {
        emoji: "🎃",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "halloween-20",
    categoryId: "halloween",
    name: "Black Cat",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      {
        emoji: "🐈‍⬛",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "🌙",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.5s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
    ],
  },
];
