import type { CardTemplate } from "../types";

export const HALLOWEEN_TEMPLATES: CardTemplate[] = [
  {
    id: "halloween-01",
    categoryId: "halloween",
    name: "Pumpkin Patch",
    layout: "centered-stack",
    themeId: "amber-gold",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "🎃", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🦇", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🕷️", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🌙", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "halloween-02",
    categoryId: "halloween",
    name: "Haunted House",
    layout: "framed",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "👻", positionClass: "top-4 left-4", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🎃", positionClass: "top-4 right-4", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "halloween-03",
    categoryId: "halloween",
    name: "Friendly Ghost",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "👻", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "halloween-04",
    categoryId: "halloween",
    name: "Witch's Brew",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "🧙‍♀️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌙", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "halloween-05",
    categoryId: "halloween",
    name: "Spooky Forest",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "sway",
    ornaments: [
      { emoji: "🌲", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🦉", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🎃", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🦇", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "halloween-06",
    categoryId: "halloween",
    name: "Skeleton Dance",
    layout: "ribbon",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💀", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🦴", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "halloween-07",
    categoryId: "halloween",
    name: "Orange Moon",
    layout: "polaroid",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌕", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "shimmer" }],
  },
  {
    id: "halloween-08",
    categoryId: "halloween",
    name: "Bat Cave",
    layout: "envelope",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🦇", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🦇", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "halloween-09",
    categoryId: "halloween",
    name: "Candy Haul",
    layout: "garland",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🍬", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍫", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍭", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "halloween-10",
    categoryId: "halloween",
    name: "Monster Mash",
    layout: "centered-stack",
    themeId: "violet",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🧟", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "👻", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "halloween-11",
    categoryId: "halloween",
    name: "Cauldron Magic",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "🫧", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🧪", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "halloween-12",
    categoryId: "halloween",
    name: "Jack-o-Lantern",
    layout: "banner-top",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🎃", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🕯️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "halloween-13",
    categoryId: "halloween",
    name: "Vampire Night",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🧛", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌙", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "halloween-14",
    categoryId: "halloween",
    name: "Spider Web",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🕸️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🕷️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "spin-slow" },
    ],
  },
  {
    id: "halloween-15",
    categoryId: "halloween",
    name: "Autumn Spooky",
    layout: "minimal-serif",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🍂", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "float" }],
  },
  {
    id: "halloween-16",
    categoryId: "halloween",
    name: "Trick or Treat",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🍬", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🎃", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "halloween-17",
    categoryId: "halloween",
    name: "Eerie Purple",
    layout: "polaroid",
    themeId: "violet",
    primaryAnimation: "pulse-soft",
    ornaments: [{ emoji: "🔮", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "shimmer" }],
  },
  {
    id: "halloween-18",
    categoryId: "halloween",
    name: "Haunted Garland",
    layout: "garland",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "👻", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🦇", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌙", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "halloween-19",
    categoryId: "halloween",
    name: "Cozy Halloween",
    layout: "envelope",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕯️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🎃", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "halloween-20",
    categoryId: "halloween",
    name: "Black Cat",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🐈‍⬛", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌙", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
];
