import type { CardTemplate } from "../types";

export const HOLI_TEMPLATES: CardTemplate[] = [
  {
    id: "holi-01",
    categoryId: "holi",
    name: "Color Explosion",
    layout: "starburst",
    themeId: "holi-rainbow",
    primaryAnimation: "color-splash",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎨",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🌈",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "rainbow-burst",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
      {
        emoji: "💥",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "1.1s",
      },
      {
        emoji: "🎨",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "wobbly-spin",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "holi-02",
    categoryId: "holi",
    name: "Rainbow Scatter",
    layout: "scattered",
    themeId: "holi-rainbow",
    primaryAnimation: "fade-in",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🌸",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.5s",
      },
      {
        emoji: "🎨",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "1s",
      },
      {
        emoji: "🌈",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "rainbow-burst",
        animationDelay: "0.7s",
      },
      {
        emoji: "💦",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "holi-03",
    categoryId: "holi",
    name: "Gulal Banner",
    layout: "banner-top",
    themeId: "festival-crimson",
    primaryAnimation: "wave-in",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎨",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "rubber-shake",
        animationDelay: "0s",
      },
      {
        emoji: "💦",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌈",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "rainbow-burst",
        animationDelay: "0.7s",
      },
      {
        emoji: "🎊",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "elastic-pop",
        animationDelay: "1s",
      },
    ],
  },
  {
    id: "holi-04",
    categoryId: "holi",
    name: "Playful Polaroid",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🌈",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎨",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-4xl",
        animation: "carnival",
        animationDelay: "0.5s",
      },
    ],
  },
  {
    id: "holi-05",
    categoryId: "holi",
    name: "Color Garland",
    layout: "garland",
    themeId: "marigold",
    primaryAnimation: "rise",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "🎨",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "color-splash",
        animationDelay: "0s",
      },
      {
        emoji: "🌸",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "lotus-bloom",
        animationDelay: "0.2s",
      },
      { emoji: "🎊", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "pop", animationDelay: "0.4s" },
      {
        emoji: "🌺",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "color-splash",
        animationDelay: "0.6s",
      },
      {
        emoji: "🌈",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "rainbow-burst",
        animationDelay: "0.8s",
      },
    ],
  },
];
