import type { CardTemplate } from "../types";

export const INDEPENDENCE_DAY_TEMPLATES: CardTemplate[] = [
  {
    id: "independence-day-01",
    categoryId: "independence-day",
    name: "Fireworks Spectacular",
    layout: "centered-stack",
    themeId: "patriotic",
    primaryAnimation: "shimmer",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎇",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.5s",
      },
      {
        emoji: "🇺🇸",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "zoom-pulse",
        animationDelay: "0.3s",
      },
      {
        emoji: "💥",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "1s",
      },
      {
        emoji: "🎆",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "firework-burst",
        animationDelay: "1.4s",
      },
      {
        emoji: "⭐",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "independence-day-02",
    categoryId: "independence-day",
    name: "Stars and Stripes",
    layout: "starburst",
    themeId: "patriotic",
    primaryAnimation: "fade-in",
    particlePreset: "stars",
    ornaments: [
      {
        emoji: "⭐",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "neon-flare",
        animationDelay: "0s",
      },
      {
        emoji: "🎆",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.5s",
      },
      {
        emoji: "🎇",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "firework-burst",
        animationDelay: "1s",
      },
      {
        emoji: "⭐",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "0.3s",
      },
      {
        emoji: "🇺🇸",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.8s",
      },
    ],
  },
  {
    id: "independence-day-03",
    categoryId: "independence-day",
    name: "July 4th Banner",
    layout: "banner-top",
    themeId: "patriotic",
    primaryAnimation: "wave-in",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎇",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.6s",
      },
      {
        emoji: "⭐",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🇺🇸",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.9s",
      },
    ],
  },
  {
    id: "independence-day-04",
    categoryId: "independence-day",
    name: "Freedom Garland",
    layout: "garland",
    themeId: "patriotic",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎇",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "firework-burst",
        animationDelay: "0.4s",
      },
      {
        emoji: "🇺🇸",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "zoom-pulse",
        animationDelay: "0.6s",
      },
    ],
  },
];
