import type { CardTemplate } from "../types";

export const JUST_BECAUSE_TEMPLATES: CardTemplate[] = [
  {
    id: "just-because-01",
    categoryId: "just-because",
    name: "Thinking of You",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "just-because-02",
    categoryId: "just-because",
    name: "Sunny Day",
    layout: "framed",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🌻", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-03",
    categoryId: "just-because",
    name: "Just Because Banner",
    layout: "banner-top",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌊", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-04",
    categoryId: "just-because",
    name: "Sweet Polaroid",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💜", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "just-because-05",
    categoryId: "just-because",
    name: "Floral Ribbon",
    layout: "ribbon",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌸", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌿", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-06",
    categoryId: "just-because",
    name: "Sparkle Burst",
    layout: "starburst",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💜", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "just-because-07",
    categoryId: "just-because",
    name: "Simple Thought",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
  {
    id: "just-because-08",
    categoryId: "just-because",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-09",
    categoryId: "just-because",
    name: "Garden Scatter",
    layout: "scattered",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍀", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌿", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-10",
    categoryId: "just-because",
    name: "Nature Garland",
    layout: "garland",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍀", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌻", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "just-because-11",
    categoryId: "just-because",
    name: "Rose Thought",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "just-because-12",
    categoryId: "just-because",
    name: "Amber Warmth",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💛", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌻", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "just-because-13",
    categoryId: "just-because",
    name: "Peach Banner",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "just-because-14",
    categoryId: "just-because",
    name: "Midnight Thought",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌙", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "⭐", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "just-because-15",
    categoryId: "just-because",
    name: "Violet Ribbon",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "just-because-16",
    categoryId: "just-because",
    name: "Sunshine Starburst",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "just-because-17",
    categoryId: "just-because",
    name: "Lavender Garland",
    layout: "garland",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "just-because-18",
    categoryId: "just-because",
    name: "Sky Envelope",
    layout: "envelope",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌤️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "just-because-19",
    categoryId: "just-because",
    name: "Rose Polaroid",
    layout: "polaroid",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "just-because-20",
    categoryId: "just-because",
    name: "Minimal Wish",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌿", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
