import type { CardTemplate } from "../types";

export const MISS_YOU_TEMPLATES: CardTemplate[] = [
  {
    id: "miss-you-01",
    categoryId: "miss-you",
    name: "Missing You",
    layout: "centered-stack",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💙", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🕊️", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "miss-you-02",
    categoryId: "miss-you",
    name: "Gentle Frame",
    layout: "framed",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "miss-you-03",
    categoryId: "miss-you",
    name: "Blue Banner",
    layout: "banner-top",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌊", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "miss-you-04",
    categoryId: "miss-you",
    name: "Memory Polaroid",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💛", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "miss-you-05",
    categoryId: "miss-you",
    name: "Soft Ribbon",
    layout: "ribbon",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-06",
    categoryId: "miss-you",
    name: "Night Starburst",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌙", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "miss-you-07",
    categoryId: "miss-you",
    name: "Quiet Thought",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🕊️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "float" }],
  },
  {
    id: "miss-you-08",
    categoryId: "miss-you",
    name: "Heart Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💌", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💜", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-09",
    categoryId: "miss-you",
    name: "Blossom Scatter",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌺", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-10",
    categoryId: "miss-you",
    name: "Dove Garland",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕊️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💙", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "☁️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "miss-you-11",
    categoryId: "miss-you",
    name: "Mint Comfort",
    layout: "centered-stack",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-12",
    categoryId: "miss-you",
    name: "Rose Frame",
    layout: "framed",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-13",
    categoryId: "miss-you",
    name: "Peach Banner",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "miss-you-14",
    categoryId: "miss-you",
    name: "Violet Scatter",
    layout: "scattered",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "💐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "miss-you-15",
    categoryId: "miss-you",
    name: "Amber Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💛", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌻", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "miss-you-16",
    categoryId: "miss-you",
    name: "Warm Polaroid",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🧡", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "miss-you-17",
    categoryId: "miss-you",
    name: "Gentle Starburst",
    layout: "starburst",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💜", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "miss-you-18",
    categoryId: "miss-you",
    name: "Emerald Garland",
    layout: "garland",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💚", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌱", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "miss-you-19",
    categoryId: "miss-you",
    name: "Night Envelope",
    layout: "envelope",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌙", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "⭐", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "miss-you-20",
    categoryId: "miss-you",
    name: "Simple Longing",
    layout: "minimal-serif",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💙", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
];
