import type { CardTemplate } from "../types";

export const MOTHERS_DAY_TEMPLATES: CardTemplate[] = [
  {
    id: "mothers-day-01",
    categoryId: "mothers-day",
    name: "Mom's Garden",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "💕", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-02",
    categoryId: "mothers-day",
    name: "Rose Frame",
    layout: "framed",
    themeId: "rose-garden",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌹", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-03",
    categoryId: "mothers-day",
    name: "Spring Banner",
    layout: "banner-top",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌸", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💐", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-04",
    categoryId: "mothers-day",
    name: "Floral Polaroid",
    layout: "polaroid",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌹", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "mothers-day-05",
    categoryId: "mothers-day",
    name: "Love Ribbon",
    layout: "ribbon",
    themeId: "peach",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "❤️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌹", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "mothers-day-06",
    categoryId: "mothers-day",
    name: "Blossom Starburst",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-07",
    categoryId: "mothers-day",
    name: "Elegant Mom",
    layout: "minimal-serif",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌹", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "float" }],
  },
  {
    id: "mothers-day-08",
    categoryId: "mothers-day",
    name: "Love Envelope",
    layout: "envelope",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💌", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "mothers-day-09",
    categoryId: "mothers-day",
    name: "Garden Scatter",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "💐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-10",
    categoryId: "mothers-day",
    name: "Flower Garland",
    layout: "garland",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌺", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "mothers-day-11",
    categoryId: "mothers-day",
    name: "Lavender Mom",
    layout: "centered-stack",
    themeId: "lavender",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "mothers-day-12",
    categoryId: "mothers-day",
    name: "Peach Love",
    layout: "framed",
    themeId: "peach",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🧡", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "mothers-day-13",
    categoryId: "mothers-day",
    name: "Sunshine Mom",
    layout: "banner-top",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🌻", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-14",
    categoryId: "mothers-day",
    name: "Amber Mom",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌻", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💛", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "mothers-day-15",
    categoryId: "mothers-day",
    name: "Violet Mom",
    layout: "scattered",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "💐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "mothers-day-16",
    categoryId: "mothers-day",
    name: "Emerald Mom",
    layout: "starburst",
    themeId: "emerald",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "mothers-day-17",
    categoryId: "mothers-day",
    name: "Warm Mom",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🧡", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "mothers-day-18",
    categoryId: "mothers-day",
    name: "Sky Mom",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💙", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💕", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "mothers-day-19",
    categoryId: "mothers-day",
    name: "Mint Mom",
    layout: "envelope",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "mothers-day-20",
    categoryId: "mothers-day",
    name: "Simple Love",
    layout: "minimal-serif",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "❤️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
];
