import type { CardTemplate } from "../types";

export const NAVRATRI_TEMPLATES: CardTemplate[] = [
  {
    id: "navratri-01",
    categoryId: "navratri",
    name: "Garba Night",
    layout: "starburst",
    themeId: "festival-crimson",
    primaryAnimation: "rangoli-spin",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "💃",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🕺",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "carnival",
        animationDelay: "0.5s",
      },
      {
        emoji: "🪘",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎭",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.7s",
      },
      {
        emoji: "🌺",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "lotus-bloom",
        animationDelay: "1s",
      },
      {
        emoji: "✨",
        positionClass: "top-1/3 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
    ],
  },
  {
    id: "navratri-02",
    categoryId: "navratri",
    name: "Dandiya Delight",
    layout: "scattered",
    themeId: "saffron-gold",
    primaryAnimation: "bounce-gentle",
    particlePreset: "confetti-rain",
    ornaments: [
      {
        emoji: "🎊",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "rainbow-burst",
        animationDelay: "0s",
      },
      {
        emoji: "💃",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "pendulum",
        animationDelay: "0.4s",
      },
      {
        emoji: "🪘",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "rubber-shake",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎭",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "wobbly-spin",
        animationDelay: "0.2s",
      },
      {
        emoji: "🌸",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "lotus-bloom",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "navratri-03",
    categoryId: "navratri",
    name: "Durga Shakti",
    layout: "framed",
    themeId: "festival-crimson",
    primaryAnimation: "rise",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "🌺",
        positionClass: "top-2 left-2",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0s",
      },
      {
        emoji: "✨",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.5s",
      },
      {
        emoji: "🌸",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "zoom-pulse",
        animationDelay: "0.8s",
      },
      {
        emoji: "💫",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "navratri-04",
    categoryId: "navratri",
    name: "Nine Nights Garland",
    layout: "garland",
    themeId: "marigold",
    primaryAnimation: "fade-in",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "🎭",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "peacock-dance",
        animationDelay: "0s",
      },
      {
        emoji: "🌺",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "lotus-bloom",
        animationDelay: "0.2s",
      },
      {
        emoji: "✨",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.4s",
      },
      {
        emoji: "🪘",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "rubber-shake",
        animationDelay: "0.6s",
      },
      { emoji: "💃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "sway", animationDelay: "0.8s" },
    ],
  },
  {
    id: "navratri-05",
    categoryId: "navratri",
    name: "Festive Envelope",
    layout: "envelope",
    themeId: "holi-rainbow",
    primaryAnimation: "drop-in",
    particlePreset: "petals",
    ornaments: [
      {
        emoji: "💃",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0s",
      },
      {
        emoji: "🌸",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-5xl",
        animation: "lotus-bloom",
        animationDelay: "0.3s",
      },
      {
        emoji: "🪘",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "rubber-shake",
        animationDelay: "0.6s",
      },
    ],
  },
];
