import type { CardTemplate } from "../types";

export const NEW_YEAR_TEMPLATES: CardTemplate[] = [
  {
    id: "new-year-01",
    categoryId: "new-year",
    name: "Fireworks",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🎆", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🎇", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-02",
    categoryId: "new-year",
    name: "Gold Countdown",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🥂", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "🍾", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
    ],
  },
  {
    id: "new-year-03",
    categoryId: "new-year",
    name: "New Year Banner",
    layout: "banner-top",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🎆", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🎇", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-04",
    categoryId: "new-year",
    name: "Champagne Polaroid",
    layout: "polaroid",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [{ emoji: "🥂", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "shimmer" }],
  },
  {
    id: "new-year-05",
    categoryId: "new-year",
    name: "Star Ribbon",
    layout: "ribbon",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-06",
    categoryId: "new-year",
    name: "Starburst NY",
    layout: "starburst",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌟", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-07",
    categoryId: "new-year",
    name: "Elegant New Year",
    layout: "minimal-serif",
    themeId: "midnight",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "✨", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "twinkle" }],
  },
  {
    id: "new-year-08",
    categoryId: "new-year",
    name: "Champagne Envelope",
    layout: "envelope",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍾", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "🥂", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "new-year-09",
    categoryId: "new-year",
    name: "Firework Scatter",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🎆", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🎇", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-10",
    categoryId: "new-year",
    name: "Star Garland",
    layout: "garland",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "✨", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌟", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💫", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎆", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "new-year-11",
    categoryId: "new-year",
    name: "Violet New Year",
    layout: "centered-stack",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🎆", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-12",
    categoryId: "new-year",
    name: "Sky Celebration",
    layout: "framed",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌟", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-13",
    categoryId: "new-year",
    name: "Rose New Year",
    layout: "banner-top",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🎆", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-14",
    categoryId: "new-year",
    name: "Lavender NY",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "shimmer",
    ornaments: [{ emoji: "💜", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" }],
  },
  {
    id: "new-year-15",
    categoryId: "new-year",
    name: "Emerald New Year",
    layout: "ribbon",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "✨", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-16",
    categoryId: "new-year",
    name: "Warm New Year",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🥂", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "shimmer" },
      { emoji: "🍾", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "bounce-gentle" },
      { emoji: "⭐", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-17",
    categoryId: "new-year",
    name: "Mint Fresh Year",
    layout: "banner-top",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌱", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "✨", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-18",
    categoryId: "new-year",
    name: "Champagne Garland",
    layout: "garland",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🥂", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍾", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎆", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "new-year-19",
    categoryId: "new-year",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌟", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "new-year-20",
    categoryId: "new-year",
    name: "Simple New Year",
    layout: "minimal-serif",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌟", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "twinkle" }],
  },
];
