import type { CardTemplate } from "../types";

export const NEW_YEAR_TEMPLATES: CardTemplate[] = [
  {
    id: "new-year-01",
    categoryId: "new-year",
    name: "Fireworks Countdown",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎇",
        positionClass: "top-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.5s",
      },
      {
        emoji: "🎆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "firework-burst",
        animationDelay: "1s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "🌟",
        positionClass: "top-1/3 left-1",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "0.7s",
      },
    ],
  },
  {
    id: "new-year-02",
    categoryId: "new-year",
    name: "Gold Countdown",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🥂",
        positionClass: "top-2 left-2",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0s",
      },
      {
        emoji: "🍾",
        positionClass: "top-2 right-2",
        sizeClass: "text-5xl",
        animation: "mega-bounce",
        animationDelay: "0.5s",
      },
      {
        emoji: "✨",
        positionClass: "bottom-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-2 right-2",
        sizeClass: "text-4xl",
        animation: "rainbow-burst",
        animationDelay: "0.3s",
      },
    ],
  },
  {
    id: "new-year-03",
    categoryId: "new-year",
    name: "New Year Banner",
    layout: "banner-top",
    themeId: "midnight",
    primaryAnimation: "rise",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎇",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0.6s",
      },
      {
        emoji: "🌟",
        positionClass: "top-2 left-2",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.3s",
      },
      {
        emoji: "💫",
        positionClass: "top-2 right-2",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "0.9s",
      },
    ],
  },
  {
    id: "new-year-04",
    categoryId: "new-year",
    name: "Celebration Starburst",
    layout: "starburst",
    themeId: "saffron-gold",
    primaryAnimation: "glow-pulse",
    particlePreset: "fireworks",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "🎉",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "carnival",
        animationDelay: "0.4s",
      },
      {
        emoji: "🥂",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎊",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "rainbow-burst",
        animationDelay: "1.2s",
      },
      {
        emoji: "✨",
        positionClass: "top-1/2 right-1",
        sizeClass: "text-4xl",
        animation: "neon-flare",
        animationDelay: "0.6s",
      },
    ],
  },
  {
    id: "new-year-05",
    categoryId: "new-year",
    name: "Champagne Scatter",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    particlePreset: "sparkles",
    ornaments: [
      {
        emoji: "🍾",
        positionClass: "top-1 left-1",
        sizeClass: "text-6xl",
        animation: "mega-bounce",
        animationDelay: "0s",
      },
      {
        emoji: "🥂",
        positionClass: "top-1 right-1",
        sizeClass: "text-5xl",
        animation: "pendulum",
        animationDelay: "0.4s",
      },
      {
        emoji: "🎆",
        positionClass: "bottom-1 left-1",
        sizeClass: "text-5xl",
        animation: "firework-burst",
        animationDelay: "0.8s",
      },
      {
        emoji: "🎉",
        positionClass: "bottom-1 right-1",
        sizeClass: "text-5xl",
        animation: "elastic-pop",
        animationDelay: "0.2s",
      },
      {
        emoji: "💫",
        positionClass: "top-1/2 left-1",
        sizeClass: "text-4xl",
        animation: "spin-grow",
        animationDelay: "1.1s",
      },
    ],
  },
  {
    id: "new-year-06",
    categoryId: "new-year",
    name: "New Year Garland",
    layout: "garland",
    themeId: "midnight",
    primaryAnimation: "rise",
    ornaments: [
      {
        emoji: "🎆",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "firework-burst",
        animationDelay: "0s",
      },
      {
        emoji: "⭐",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "neon-flare",
        animationDelay: "0.2s",
      },
      {
        emoji: "🎇",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "firework-burst",
        animationDelay: "0.4s",
      },
      {
        emoji: "🌟",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "spin-grow",
        animationDelay: "0.6s",
      },
      {
        emoji: "🎆",
        positionClass: "top-0 left-0",
        sizeClass: "text-2xl",
        animation: "firework-burst",
        animationDelay: "0.8s",
      },
    ],
  },
];
