import type { CardTemplate } from "../types";

export const SYMPATHY_TEMPLATES: CardTemplate[] = [
  {
    id: "sympathy-01",
    categoryId: "sympathy",
    name: "Gentle Comfort",
    layout: "centered-stack",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🕊️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-02",
    categoryId: "sympathy",
    name: "Lily Frame",
    layout: "framed",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌷", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-03",
    categoryId: "sympathy",
    name: "Soft Banner",
    layout: "banner-top",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕊️", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-04",
    categoryId: "sympathy",
    name: "Peaceful Polaroid",
    layout: "polaroid",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🕊️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "sympathy-05",
    categoryId: "sympathy",
    name: "Dove Ribbon",
    layout: "ribbon",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🕊️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌷", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-06",
    categoryId: "sympathy",
    name: "Gentle Starburst",
    layout: "starburst",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-07",
    categoryId: "sympathy",
    name: "Quiet Words",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🕊️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "float" }],
  },
  {
    id: "sympathy-08",
    categoryId: "sympathy",
    name: "Caring Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕊️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-09",
    categoryId: "sympathy",
    name: "Blossom Scatter",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🕊️", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌺", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-10",
    categoryId: "sympathy",
    name: "Dove Garland",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕊️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "sympathy-11",
    categoryId: "sympathy",
    name: "Rose Comfort",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🕊️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-12",
    categoryId: "sympathy",
    name: "Peaceful Blue",
    layout: "framed",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🕊️", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💙", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-13",
    categoryId: "sympathy",
    name: "Violet Comfort",
    layout: "banner-top",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🕊️", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-14",
    categoryId: "sympathy",
    name: "Lily Scatter",
    layout: "scattered",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🕊️", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌺", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "sympathy-15",
    categoryId: "sympathy",
    name: "Emerald Peace",
    layout: "ribbon",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌿", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🕊️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-16",
    categoryId: "sympathy",
    name: "Warm Comfort",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "sympathy-17",
    categoryId: "sympathy",
    name: "Soft Garland",
    layout: "garland",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🕊️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "sympathy-18",
    categoryId: "sympathy",
    name: "Mint Envelope",
    layout: "envelope",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌱", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🕊️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-19",
    categoryId: "sympathy",
    name: "Blue Starburst",
    layout: "starburst",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💙", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🕊️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "sympathy-20",
    categoryId: "sympathy",
    name: "Simple Sympathy",
    layout: "minimal-serif",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌷", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
];
