import type { CardTemplate } from "../types";

export const THANKSGIVING_TEMPLATES: CardTemplate[] = [
  {
    id: "thanksgiving-01",
    categoryId: "thanksgiving",
    name: "Harvest Table",
    layout: "centered-stack",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🦃", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍂", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌽", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🍁", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-02",
    categoryId: "thanksgiving",
    name: "Grateful Hearts",
    layout: "framed",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "❤️", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🍂", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thanksgiving-03",
    categoryId: "thanksgiving",
    name: "Autumn Leaves",
    layout: "scattered",
    themeId: "amber-gold",
    primaryAnimation: "sway",
    ornaments: [
      { emoji: "🍁", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🍂", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌰", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "bounce-gentle" },
      { emoji: "🍁", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "thanksgiving-04",
    categoryId: "thanksgiving",
    name: "Pumpkin Pie",
    layout: "banner-top",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🥧", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🎃", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-05",
    categoryId: "thanksgiving",
    name: "Fall Garland",
    layout: "garland",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍁", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🦃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌽", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🍂", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🎃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thanksgiving-06",
    categoryId: "thanksgiving",
    name: "Turkey Day",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🦃", positionClass: "bottom-4 left-4", sizeClass: "text-3xl", animation: "sway" }],
  },
  {
    id: "thanksgiving-07",
    categoryId: "thanksgiving",
    name: "Warm Welcome",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🏡", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "thanksgiving-08",
    categoryId: "thanksgiving",
    name: "Apple Cider",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍎", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "☕", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "shimmer" },
    ],
  },
  {
    id: "thanksgiving-09",
    categoryId: "thanksgiving",
    name: "Sunflower Fields",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌻", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌾", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-10",
    categoryId: "thanksgiving",
    name: "Cranberry Harvest",
    layout: "centered-stack",
    themeId: "peach",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍒", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🍂", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-11",
    categoryId: "thanksgiving",
    name: "Cornucopia",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌽", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🍇", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thanksgiving-12",
    categoryId: "thanksgiving",
    name: "Evening Glow",
    layout: "minimal-serif",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🕯️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "twinkle" }],
  },
  {
    id: "thanksgiving-13",
    categoryId: "thanksgiving",
    name: "Forest Walk",
    layout: "scattered",
    themeId: "emerald",
    primaryAnimation: "sway",
    ornaments: [
      { emoji: "🌲", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍂", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🦌", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thanksgiving-14",
    categoryId: "thanksgiving",
    name: "Golden Starburst",
    layout: "starburst",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "thanksgiving-15",
    categoryId: "thanksgiving",
    name: "Cinnamon Spice",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍎", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🍂", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-16",
    categoryId: "thanksgiving",
    name: "Family Feast",
    layout: "garland",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🍽️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🥂", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🦃", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "❤️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thanksgiving-17",
    categoryId: "thanksgiving",
    name: "Harvest Moon",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌕", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "shimmer" },
      { emoji: "🍂", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thanksgiving-18",
    categoryId: "thanksgiving",
    name: "Pecan Pie",
    layout: "polaroid",
    themeId: "amber-gold",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🥧", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "thanksgiving-19",
    categoryId: "thanksgiving",
    name: "Grateful & Blessed",
    layout: "ribbon",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🍀", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "✨", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "thanksgiving-20",
    categoryId: "thanksgiving",
    name: "Simple Thanks",
    layout: "envelope",
    themeId: "slate-clean",
    primaryAnimation: "rise",
    ornaments: [{ emoji: "🍂", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" }],
  },
];
