import type { CardTemplate } from "../types";

export const THANK_YOU_TEMPLATES: CardTemplate[] = [
  {
    id: "thank-you-01",
    categoryId: "thank-you",
    name: "Heartfelt Thanks",
    layout: "centered-stack",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🙏", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💚", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thank-you-02",
    categoryId: "thank-you",
    name: "Floral Thank You",
    layout: "framed",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌷", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-03",
    categoryId: "thank-you",
    name: "Gratitude Banner",
    layout: "banner-top",
    themeId: "sunshine",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "✨", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "thank-you-04",
    categoryId: "thank-you",
    name: "Thank You Polaroid",
    layout: "polaroid",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🙏", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "thank-you-05",
    categoryId: "thank-you",
    name: "Golden Thanks",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💛", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thank-you-06",
    categoryId: "thank-you",
    name: "Starburst Gratitude",
    layout: "starburst",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "✨", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "thank-you-07",
    categoryId: "thank-you",
    name: "Minimal Thanks",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌿", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "sway" }],
  },
  {
    id: "thank-you-08",
    categoryId: "thank-you",
    name: "Gratitude Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🙏", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-09",
    categoryId: "thank-you",
    name: "Garden Thanks",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌷", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🍀", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌿", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "thank-you-10",
    categoryId: "thank-you",
    name: "Flower Garland",
    layout: "garland",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🙏", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thank-you-11",
    categoryId: "thank-you",
    name: "Violet Gratitude",
    layout: "centered-stack",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-12",
    categoryId: "thank-you",
    name: "Peach Thanks",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-13",
    categoryId: "thank-you",
    name: "Tea Thanks",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [{ emoji: "☕", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "none" }],
  },
  {
    id: "thank-you-14",
    categoryId: "thank-you",
    name: "Emerald Frame",
    layout: "framed",
    themeId: "emerald",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌿", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🍃", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thank-you-15",
    categoryId: "thank-you",
    name: "Sky Thanks",
    layout: "starburst",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "☁️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌤️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-16",
    categoryId: "thank-you",
    name: "Amber Ribbon",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌻", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "⭐", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "thank-you-17",
    categoryId: "thank-you",
    name: "Midnight Gratitude",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "⭐", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "thank-you-18",
    categoryId: "thank-you",
    name: "Sunshine Gratitude",
    layout: "garland",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌻", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💛", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "⭐", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thank-you-19",
    categoryId: "thank-you",
    name: "Lavender Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thank-you-20",
    categoryId: "thank-you",
    name: "Simple Thank You",
    layout: "minimal-serif",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌿", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
