import type { CardTemplate } from "../types";

export const THINKING_OF_YOU_TEMPLATES: CardTemplate[] = [
  {
    id: "thinking-of-you-01",
    categoryId: "thinking-of-you",
    name: "In Your Thoughts",
    layout: "centered-stack",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💭", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💙", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-02",
    categoryId: "thinking-of-you",
    name: "Gentle Frame",
    layout: "framed",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💜", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-03",
    categoryId: "thinking-of-you",
    name: "Thinking Banner",
    layout: "banner-top",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🍃", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "thinking-of-you-04",
    categoryId: "thinking-of-you",
    name: "Memory Polaroid",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💛", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "thinking-of-you-05",
    categoryId: "thinking-of-you",
    name: "Soft Ribbon",
    layout: "ribbon",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-06",
    categoryId: "thinking-of-you",
    name: "Gentle Starburst",
    layout: "starburst",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "☁️", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "🌤️", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thinking-of-you-07",
    categoryId: "thinking-of-you",
    name: "Quiet Thought",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🕊️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "float" }],
  },
  {
    id: "thinking-of-you-08",
    categoryId: "thinking-of-you",
    name: "Heart Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💌", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💜", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-09",
    categoryId: "thinking-of-you",
    name: "Blossom Scatter",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌺", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌼", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "thinking-of-you-10",
    categoryId: "thinking-of-you",
    name: "Dove Garland",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🕊️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💙", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "☁️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thinking-of-you-11",
    categoryId: "thinking-of-you",
    name: "Emerald Thought",
    layout: "centered-stack",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-12",
    categoryId: "thinking-of-you",
    name: "Amber Warmth",
    layout: "framed",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌻", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💛", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-13",
    categoryId: "thinking-of-you",
    name: "Mint Scatter",
    layout: "scattered",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍀", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍃", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌱", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "thinking-of-you-14",
    categoryId: "thinking-of-you",
    name: "Violet Thought",
    layout: "ribbon",
    themeId: "violet",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thinking-of-you-15",
    categoryId: "thinking-of-you",
    name: "Peach Banner",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "thinking-of-you-16",
    categoryId: "thinking-of-you",
    name: "Warm Polaroid",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🧡", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "thinking-of-you-17",
    categoryId: "thinking-of-you",
    name: "Simple Starburst",
    layout: "starburst",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "💜", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-18",
    categoryId: "thinking-of-you",
    name: "Sunshine Envelope",
    layout: "envelope",
    themeId: "sunshine",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "☀️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "shimmer" },
      { emoji: "💛", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "thinking-of-you-19",
    categoryId: "thinking-of-you",
    name: "Floral Garland",
    layout: "garland",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌷", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💕", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "thinking-of-you-20",
    categoryId: "thinking-of-you",
    name: "Pure Thought",
    layout: "minimal-serif",
    themeId: "mint",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌱", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
