import type { CardTemplate } from "../types";

export const VALENTINES_TEMPLATES: CardTemplate[] = [
  {
    id: "valentines-01",
    categoryId: "valentines",
    name: "My Valentine",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "❤️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "💕", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌹", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💖", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-02",
    categoryId: "valentines",
    name: "Rose Frame",
    layout: "framed",
    themeId: "rose-garden",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌹", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-03",
    categoryId: "valentines",
    name: "Hearts Banner",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💕", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "💝", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-04",
    categoryId: "valentines",
    name: "Love Polaroid",
    layout: "polaroid",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💖", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" }],
  },
  {
    id: "valentines-05",
    categoryId: "valentines",
    name: "Heart Ribbon",
    layout: "ribbon",
    themeId: "rose-garden",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "❤️", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌹", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "valentines-06",
    categoryId: "valentines",
    name: "Love Starburst",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "💕", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "💖", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-07",
    categoryId: "valentines",
    name: "Elegant Love",
    layout: "minimal-serif",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "❤️", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
  {
    id: "valentines-08",
    categoryId: "valentines",
    name: "Love Letter",
    layout: "envelope",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💌", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "float" },
      { emoji: "❤️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-09",
    categoryId: "valentines",
    name: "Rose Scatter",
    layout: "scattered",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "❤️", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "💕", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "💖", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-10",
    categoryId: "valentines",
    name: "Heart Garland",
    layout: "garland",
    themeId: "rose-garden",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "❤️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💕", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💖", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💝", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "valentines-11",
    categoryId: "valentines",
    name: "Lavender Love",
    layout: "centered-stack",
    themeId: "lavender",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "💜", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "valentines-12",
    categoryId: "valentines",
    name: "Violet Passion",
    layout: "framed",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌷", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "valentines-13",
    categoryId: "valentines",
    name: "Midnight Love",
    layout: "scattered",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "❤️", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "✨", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "💫", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "twinkle" },
      { emoji: "🌹", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "float" },
    ],
  },
  {
    id: "valentines-14",
    categoryId: "valentines",
    name: "Peach Sweetness",
    layout: "banner-top",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "valentines-15",
    categoryId: "valentines",
    name: "Rose Polaroid",
    layout: "polaroid",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌹", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "valentines-16",
    categoryId: "valentines",
    name: "Pure Love",
    layout: "minimal-serif",
    themeId: "lavender",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "💜", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "pulse-soft" }],
  },
  {
    id: "valentines-17",
    categoryId: "valentines",
    name: "Amber Hearts",
    layout: "ribbon",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💛", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌻", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "valentines-18",
    categoryId: "valentines",
    name: "Warmth Garland",
    layout: "garland",
    themeId: "peach",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🧡", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "❤️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌹", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💕", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "valentines-19",
    categoryId: "valentines",
    name: "Starburst Hearts",
    layout: "starburst",
    themeId: "rose-garden",
    primaryAnimation: "pulse-soft",
    ornaments: [
      { emoji: "💗", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "💓", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "valentines-20",
    categoryId: "valentines",
    name: "Sweet Envelope",
    layout: "envelope",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "💌", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
];
