import type { CardTemplate } from "../types";

export const WELCOME_TEMPLATES: CardTemplate[] = [
  {
    id: "welcome-01",
    categoryId: "welcome",
    name: "Open Arms",
    layout: "centered-stack",
    themeId: "sky-blue",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🏠", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "💙", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "welcome-02",
    categoryId: "welcome",
    name: "Sunny Welcome",
    layout: "framed",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "☀️", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "spin-slow" },
      { emoji: "🌻", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "welcome-03",
    categoryId: "welcome",
    name: "Welcome Banner",
    layout: "banner-top",
    themeId: "emerald",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🏠", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "welcome-04",
    categoryId: "welcome",
    name: "Home Polaroid",
    layout: "polaroid",
    themeId: "warm-cream",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🏠", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "float" }],
  },
  {
    id: "welcome-05",
    categoryId: "welcome",
    name: "Green Ribbon",
    layout: "ribbon",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "🍀", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "sway" },
    ],
  },
  {
    id: "welcome-06",
    categoryId: "welcome",
    name: "Star Welcome",
    layout: "starburst",
    themeId: "sunshine",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "⭐", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "welcome-07",
    categoryId: "welcome",
    name: "Elegant Welcome",
    layout: "minimal-serif",
    themeId: "slate-clean",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🏠", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
  {
    id: "welcome-08",
    categoryId: "welcome",
    name: "Welcome Envelope",
    layout: "envelope",
    themeId: "sky-blue",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💙", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌤️", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "welcome-09",
    categoryId: "welcome",
    name: "Garden Welcome",
    layout: "scattered",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌸", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌷", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🌿", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "sway" },
      { emoji: "🍀", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "sway" },
    ],
  },
  {
    id: "welcome-10",
    categoryId: "welcome",
    name: "Home Garland",
    layout: "garland",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🏠", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌸", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌟", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💛", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "welcome-11",
    categoryId: "welcome",
    name: "Rose Welcome",
    layout: "centered-stack",
    themeId: "rose-garden",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "🌹", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "float" },
      { emoji: "💕", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "welcome-12",
    categoryId: "welcome",
    name: "Violet Welcome",
    layout: "framed",
    themeId: "violet",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "💜", positionClass: "top-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "welcome-13",
    categoryId: "welcome",
    name: "Amber Welcome",
    layout: "banner-top",
    themeId: "amber-gold",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "🌻", positionClass: "bottom-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💛", positionClass: "bottom-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "welcome-14",
    categoryId: "welcome",
    name: "Peach Welcome",
    layout: "scattered",
    themeId: "peach",
    primaryAnimation: "bounce-gentle",
    ornaments: [
      { emoji: "🧡", positionClass: "top-2 left-2", sizeClass: "text-3xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "top-2 right-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🏠", positionClass: "bottom-2 left-2", sizeClass: "text-3xl", animation: "float" },
      { emoji: "🌟", positionClass: "bottom-2 right-2", sizeClass: "text-3xl", animation: "twinkle" },
    ],
  },
  {
    id: "welcome-15",
    categoryId: "welcome",
    name: "Lavender Welcome",
    layout: "ribbon",
    themeId: "lavender",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "💜", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🌸", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "welcome-16",
    categoryId: "welcome",
    name: "Mint Starburst",
    layout: "starburst",
    themeId: "mint",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🌿", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "sway" },
      { emoji: "💚", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "pulse-soft" },
    ],
  },
  {
    id: "welcome-17",
    categoryId: "welcome",
    name: "Sky Garland",
    layout: "garland",
    themeId: "sky-blue",
    primaryAnimation: "fade-in",
    ornaments: [
      { emoji: "☁️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌤️", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "💙", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
      { emoji: "🌟", positionClass: "top-0 left-0", sizeClass: "text-2xl", animation: "none" },
    ],
  },
  {
    id: "welcome-18",
    categoryId: "welcome",
    name: "Warm Envelope",
    layout: "envelope",
    themeId: "warm-cream",
    primaryAnimation: "rise",
    ornaments: [
      { emoji: "🧡", positionClass: "bottom-4 left-4", sizeClass: "text-2xl", animation: "pulse-soft" },
      { emoji: "🏠", positionClass: "bottom-4 right-4", sizeClass: "text-2xl", animation: "float" },
    ],
  },
  {
    id: "welcome-19",
    categoryId: "welcome",
    name: "Midnight Welcome",
    layout: "centered-stack",
    themeId: "midnight",
    primaryAnimation: "shimmer",
    ornaments: [
      { emoji: "✨", positionClass: "top-2 left-2", sizeClass: "text-2xl", animation: "twinkle" },
      { emoji: "🌟", positionClass: "top-2 right-2", sizeClass: "text-2xl", animation: "twinkle" },
    ],
  },
  {
    id: "welcome-20",
    categoryId: "welcome",
    name: "Pure Welcome",
    layout: "minimal-serif",
    themeId: "emerald",
    primaryAnimation: "fade-in",
    ornaments: [{ emoji: "🌱", positionClass: "top-4 right-4", sizeClass: "text-xl", animation: "none" }],
  },
];
